provectus/kafka-ui

kafka-ui-react-app/src/redux/reducers/consumerGroups/selectors.ts
=> fix-consumer-groups-retaining-cluster-on-cluster-switch

kafka-ui-react-app/src/components/Topics/New/CustomParams/CustomParamAction.tsx, kafka-ui-react-app/src/components/Topics/New/CustomParams/CustomParamButton.tsx, kafka-ui-react-app/src/components/Topics/New/CustomParams/CustomParamSelect.tsx, kafka-ui-react-app/src/components/Topics/New/CustomParams/CustomParamValue.tsx, kafka-ui-react-app/src/components/Topics/New/CustomParams/CustomParams.tsx
=> redesign-topics-adding-custom-params-design

kafka-ui-react-app/src/components/Topics/New/CustomParams/CustomParams.tsx, kafka-ui-react-app/src/redux/api/topics.ts
https://github.com/provectus/kafka-ui/issues/14
=> issue-14/update-custom-params-key-to-work-as-object-not-array

Jenkinsfile
"origin/master" is the wrong branch name because "origin" is a just a pointer to git remote, the valid value of the branch is "master"
=> Fix release pipeline

kafka-ui-react-app/package-lock.json, kafka-ui-react-app/package.json, kafka-ui-react-app/src/components/Topics/Details/Messages/Messages.tsx
Implemented display of JSON content of topic message as tree.
=> Feature#108: Topic message content tree view

kafka-ui-react-app/package-lock.json
=> Fixing release build.

kafka-ui-react-app/README.md
=> Updated readme for react app

kafka-ui-react-app/.eslintrc.json, kafka-ui-react-app/src/components/Topics/Details/Messages/Messages.tsx, kafka-ui-react-app/src/redux/store/configureStore/dev.ts, kafka-ui-react-app/src/serviceWorker.ts
"Any" types replaced with correct types
=> Unexpected any types replaced

kafka-ui-api/src/main/java/com/provectus/kafka/ui/cluster/service/ClusterService.java, kafka-ui-react-app/src/components/Topics/Details/Messages/MessageItem.tsx, kafka-ui-react-app/src/components/Topics/Details/Messages/Messages.tsx, kafka-ui-react-app/src/components/Topics/Details/Messages/MessagesTable.tsx, kafka-ui-react-app/src/redux/reducers/topics/reducer.ts
Messages component decomposed and refactored
=> Messages component refactoring

.github/workflows/maven.yml
Simple workflow for testing applications build process, going to add separate one for testing UI app with `npm test` and `npm run lint`
=> Added workflow for github actions

kafka-ui-api/src/main/java/com/provectus/kafka/ui/cluster/service/SchemaRegistryService.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/zookeeper/ZookeeperService.java
1. Fixed creating zookeeper client on every call
2. Removed `formatted` preview feature usage
=> Fixed Zookeeper connection leak

kafka-ui-react-app/src/redux/reducers/brokers/reducer.ts, kafka-ui-react-app/src/redux/reducers/clusters/reducer.ts, kafka-ui-react-app/src/redux/reducers/consumerGroups/reducer.ts, kafka-ui-react-app/src/redux/reducers/topics/reducer.ts
We want to write more typed code, to that we can use [getType](https://github.com/piotrwitek/typesafe-actions#gettype) helper in reducers.
=> [CHORE] Use getType in reducers

kafka-ui-contract/pom.xml, kafka-ui-react-app/openapitools.json, kafka-ui-react-app/package-lock.json, kafka-ui-react-app/package.json, kafka-ui-react-app/src/components/Dashboard/ClustersWidget/ClusterWidget.tsx, kafka-ui-react-app/src/components/Dashboard/ClustersWidget/__test__/ClusterWidget.spec.tsx, kafka-ui-react-app/src/components/Dashboard/ClustersWidget/__test__/fixtures.ts, kafka-ui-react-app/src/components/Nav/ClusterMenu.tsx, kafka-ui-react-app/src/components/Schemas/Details/__test__/Details.spec.tsx, kafka-ui-react-app/src/redux/reducers/clusters/__test__/fixtures.ts, kafka-ui-react-app/src/redux/reducers/clusters/selectors.ts
Adds and ability to build generated-sources without _**mvnw**_
=> [CHORE] Add openapi-generator-cli to generate sources on FE side

kafka-ui-api/src/main/java/com/provectus/kafka/ui/kafka/KafkaService.java
Before the fix in 5 minutes after launch:
After fix in 6 minutes after launch:
=> #168 Resolve thread leak when creating Kafka admin client

kafka-ui-api/src/main/java/com/provectus/kafka/ui/cluster/service/ClusterService.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/kafka/KafkaService.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/rest/MetricsRestController.java, kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
=> #224 added deleteTopic operation api

docker/kafka-clusters-only.yaml, docker/kafka-ui.yaml, kafka-ui-api/src/main/resources/application-local.yml
=> #197 updated confluent images versions to 5.2.4

kafka-ui-api/src/main/java/com/provectus/kafka/ui/cluster/deserialization/SchemaRegistryRecordDeserializer.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/cluster/deserialization/SchemaRegistryRecordDeserializerTest.java
=> #222 Fix npe in consumer

kafka-ui-api/src/main/java/com/provectus/kafka/ui/cluster/service/ClusterService.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/cluster/service/ConsumingService.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/kafka/KafkaService.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/rest/MetricsRestController.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/AbstractBaseTest.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/KafkaConsumerTests.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/container/KafkaConnectContainer.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/container/SchemaRegistryContainer.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/producer/KafkaTestProducer.java, kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
=> #211 Feature/clear topic messages

kafka-ui-react-app/package-lock.json, kafka-ui-react-app/package.json, kafka-ui-react-app/src/components/Schemas/List/List.tsx, kafka-ui-react-app/src/components/Schemas/New/__test__/__snapshots__/New.spec.tsx.snap, kafka-ui-react-app/src/components/Topics/List/List.tsx, kafka-ui-react-app/src/components/Topics/List/ListContainer.ts, kafka-ui-react-app/src/components/Topics/List/__tests__/List.spec.tsx, kafka-ui-react-app/src/components/common/Breadcrumb/Breadcrumb.tsx, kafka-ui-react-app/src/components/common/Breadcrumb/__tests__/Breadcrumb.spec.tsx, kafka-ui-react-app/src/components/common/Pagination/PageControl.tsx, kafka-ui-react-app/src/components/common/Pagination/Pagination.tsx, kafka-ui-react-app/src/components/common/Pagination/__tests__/PageControl.spec.tsx, kafka-ui-react-app/src/components/common/Pagination/__tests__/Pagination.spec.tsx, kafka-ui-react-app/src/components/common/Pagination/__tests__/__snapshots__/PageControl.spec.tsx.snap, kafka-ui-react-app/src/components/common/Pagination/__tests__/__snapshots__/Pagination.spec.tsx.snap, kafka-ui-react-app/src/lib/constants.ts, kafka-ui-react-app/src/lib/hooks/usePagination.ts, kafka-ui-react-app/src/redux/actions/actions.ts, kafka-ui-react-app/src/redux/actions/thunks/topics.ts, kafka-ui-react-app/src/redux/reducers/topics/reducer.ts, kafka-ui-react-app/src/redux/reducers/topics/selectors.ts
- refactor Topics
- Pagination (TODO: Specs)
PR is big, I know. Sorry
=> [#188] Pagination. Refactor topic reducer

.github/workflows/latest.yaml
Added aws-cli call for service restart
=> Delivery step for ECS

.github/workflows/master.yaml, .github/workflows/release.yaml
`master` - would be used for builds from the master branch
`latest` - would point to the latest release
=>  Image tag renaming

kafka-ui-react-app/src/components/Topics/Topic/Edit/Edit.tsx, kafka-ui-react-app/src/redux/actions/thunks/topics.ts
add topicName in updateTopic function
open topic and press edit
making changes and press submit
=> [issues-252][bug] - Topic settings form is broken

.gitignore, kafka-ui-react-app/src/components/Alert/Alert.tsx, kafka-ui-react-app/src/components/Alert/__tests__/Alert.spec.tsx, kafka-ui-react-app/src/components/Alert/__tests__/__snapshots__/Alert.spec.tsx.snap, kafka-ui-react-app/src/components/App.scss, kafka-ui-react-app/src/components/App.tsx, kafka-ui-react-app/src/components/AppContainer.tsx, kafka-ui-react-app/src/components/Schemas/New/New.tsx, kafka-ui-react-app/src/components/Topics/New/NewContainer.ts, kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/__tests__/CustomParamSelect.spec.tsx, kafka-ui-react-app/src/components/__test__/App.spec.tsx, kafka-ui-react-app/src/components/__test__/__snapshots__/App.spec.tsx.snap, kafka-ui-react-app/src/lib/errorHandling.ts, kafka-ui-react-app/src/redux/actions/__test__/actions.spec.ts, kafka-ui-react-app/src/redux/actions/__test__/thunks/schemas.spec.ts, kafka-ui-react-app/src/redux/actions/actions.ts, kafka-ui-react-app/src/redux/actions/thunks/schemas.ts, kafka-ui-react-app/src/redux/actions/thunks/topics.ts, kafka-ui-react-app/src/redux/interfaces/alerts.ts, kafka-ui-react-app/src/redux/interfaces/index.ts, kafka-ui-react-app/src/redux/reducers/alerts/__test__/fixtures.ts, kafka-ui-react-app/src/redux/reducers/alerts/__test__/reducer.spec.ts, kafka-ui-react-app/src/redux/reducers/alerts/__test__/selectors.spec.ts, kafka-ui-react-app/src/redux/reducers/alerts/reducer.ts, kafka-ui-react-app/src/redux/reducers/alerts/selectors.ts, kafka-ui-react-app/src/redux/reducers/alerts/utils.ts, kafka-ui-react-app/src/redux/reducers/index.ts
=> [CHORE] Alerts

kafka-ui-react-app/src/components/Connect/List/List.tsx, kafka-ui-react-app/src/components/Connect/List/ListItem.tsx, kafka-ui-react-app/src/components/Connect/List/__tests__/ListItem.spec.tsx, kafka-ui-react-app/src/components/Connect/List/__tests__/__snapshots__/ListItem.spec.tsx.snap, kafka-ui-react-app/src/components/common/ConfirmationModal/ConfirmationModal.tsx, kafka-ui-react-app/src/components/common/ConfirmationModal/__test__/ConfirmationModal.spec.tsx
=> Add ConfirmationModal common component

kafka-ui-react-app/src/components/Schemas/List/GlobalSchemaSelector.tsx, kafka-ui-react-app/src/components/Schemas/List/List.tsx, kafka-ui-react-app/src/components/Schemas/List/ListContainer.tsx, kafka-ui-react-app/src/components/Schemas/List/__test__/List.spec.tsx, kafka-ui-react-app/src/redux/actions/__test__/thunks/schemas.spec.ts, kafka-ui-react-app/src/redux/actions/actions.ts, kafka-ui-react-app/src/redux/actions/thunks/schemas.ts, kafka-ui-react-app/src/redux/interfaces/schema.ts, kafka-ui-react-app/src/redux/reducers/schemas/__test__/reducer.spec.ts, kafka-ui-react-app/src/redux/reducers/schemas/__test__/selectors.spec.ts, kafka-ui-react-app/src/redux/reducers/schemas/reducer.ts, kafka-ui-react-app/src/redux/reducers/schemas/selectors.ts
Now it is possible to update the global schema compatibility level:
=> Implement updating registry compatibility level

charts/kafka-ui/templates/deployment.yaml, charts/kafka-ui/templates/service.yaml
Adding service annotation to helm chart service.yaml
Updating livenessProbe readinessProbe settings
=> Adding service annotation to helm chart service.yaml

kafka-ui-react-app/package.json, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessageContent.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessageItem.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/__test__/MessageContent.spec.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/__test__/MessageItem.spec.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/__test__/Messages.spec.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/__test__/__snapshots__/MessageContent.spec.tsx.snap, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/__test__/__snapshots__/MessageItem.spec.tsx.snap, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/__test__/fixtures.ts, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/theme.ts, kafka-ui-react-app/src/theme/bulma_overrides.scss
Now the Topic Messages that are longer than 200 symbols are truncated by default.
Yes, I used a tiny bit of custom CSS, but I hope we can handle it somehow
=> Message truncation

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/pr-checks.yaml
Added  pull-request template and issue templates - bug report + feature request
Also added task checker and pr-description-enforcer - 
build should fail, if some of the checkboxes from checklist  aren't checked or PR description is default one
Isn't it a lot of checkboxes? Should we be doing something more lightweight?
**---- Screenshots---**
=> #449 adding issue templates, pr template

kafka-ui-react-app/package-lock.json, kafka-ui-react-app/package.json, kafka-ui-react-app/src/components/Connect/List/__tests__/__snapshots__/ListItem.spec.tsx.snap, kafka-ui-react-app/src/components/__tests__/__snapshots__/App.spec.tsx.snap
Bump redux from 4.0.5 to 4.1.0
=> Bump redux to 4.1.0

.github/workflows/pr-checks.yaml
=> changed pull_request to pull_request_target

kafka-ui-react-app/src/index.tsx
Add basename prop to the BrowserRouter
=> Add basename prop

kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Reverts provectus/kafka-ui#519
=> Revert "Add SeekDirection to the GET topic messages request"

kafka-ui-react-app/src/components/Topics/shared/Form/TopicForm.tsx
Because of my mistake _all_ fields in the form for editing topics were disabled, whereas only three were supposed to be. Fixed that issue.
=> Fix erroneous field disabling

kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/MessagesController.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/ConsumerPosition.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ConsumingService.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/OffsetsSeek.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/OffsetsSeekBackward.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/OffsetsSeekForward.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/RecordEmitterTest.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/util/OffsetsSeekTest.java, kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
=> #122 Seek direction backend support

kafka-ui-react-app/src/components/Cluster/__tests__/Cluster.spec.tsx
Removed the redundant "await" 
=> Removed redundant "await"

kafka-ui-react-app/src/components/Brokers/__test__/Brokers.spec.tsx, kafka-ui-react-app/src/components/Brokers/__test__/BrokersContainer.spec.tsx, kafka-ui-react-app/src/components/Brokers/__test__/__snapshots__/Brokers.spec.tsx.snap
Cover Brokers page with tests #213
=> Cover Brokers page with tests #213

kafka-ui-react-app/src/redux/actions/thunks/topics.ts
Created a function to reduce the redundancy of code.
=> Updated implementation

kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ConsumingService.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/OffsetsSeek.java
=> #122 Added messages reordering

docker/jaas/client.properties, docker/jaas/kafka_server.conf, docker/kafka-ui-sasl.yaml
=> #573 added sasl plain example

README.md, guides/SSO.md
Add a new documentation page with instructions about SSO configuration
will close #543
=> Add SSO instruction

kafka-ui-react-app/package-lock.json, kafka-ui-react-app/package.json, kafka-ui-react-app/src/components/Topics/Topic/Details/ConsumerGroups/TopicConsumerGroups.tsx
=> Bump packages

kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/BackwardRecordEmitter.java, kafka-ui-api/src/main/resources/application-sdp.yml
=> #122 Fixed npe in backward emitter

kafka-ui-react-app/src/components/Dashboard/ClustersWidget/__test__/ClustersWidget.spec.tsx, kafka-ui-react-app/src/components/Dashboard/ClustersWidget/__test__/ClustersWidgetContainer.spec.tsx, kafka-ui-react-app/src/components/Dashboard/__test__/Dashboard.spec.tsx
=> Cover Dashboard page with tests

README.md
in my case, somehow running everything in single deployment pod i got error complaining that 8080 is already taken, and did not found any docs here about ability to change it
it is built in spring boot feature, just clarifying that option in readme, nothing more
=> option to override listening port

kafka-ui-react-app/src/components/ConsumerGroups/Details/Details.tsx, kafka-ui-react-app/src/components/ConsumerGroups/Details/DetailsContainer.ts, kafka-ui-react-app/src/components/ConsumerGroups/Details/__tests__/Details.spec.tsx, kafka-ui-react-app/src/components/ConsumerGroups/Details/__tests__/__snapshots__/Details.spec.tsx.snap, kafka-ui-react-app/src/components/Topics/Topic/Details/ConsumerGroups/TopicConsumerGroups.tsx, kafka-ui-react-app/src/redux/actions/__test__/actions.spec.ts, kafka-ui-react-app/src/redux/actions/__test__/thunks/consumerGroups.spec.ts, kafka-ui-react-app/src/redux/actions/actions.ts, kafka-ui-react-app/src/redux/actions/thunks/consumerGroups.ts, kafka-ui-react-app/src/redux/reducers/consumerGroups/__test__/reducer.spec.ts, kafka-ui-react-app/src/redux/reducers/consumerGroups/reducer.ts, kafka-ui-react-app/src/redux/reducers/consumerGroups/selectors.ts
Implemented frontend for the consumer group deleting:
=> Implement consumer group deleting

kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/BackwardRecordEmitter.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/OffsetsSeek.java
=> #122 Fixed compacted topics backward reading

kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/ExtendedAdminClient.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/KafkaCluster.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaService.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/ClusterUtil.java, kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
=> Added cluster version to api

kafka-ui-react-app/src/components/Topics/List/List.tsx, kafka-ui-react-app/src/components/Topics/List/ListItem.tsx, kafka-ui-react-app/src/components/Topics/List/__tests__/__snapshots__/List.spec.tsx.snap
Added number of messages and size columns to Topic List
=> #633 Added number of messages and size columns to Topic List

kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClusterService.java, kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
=> adding sorting parameter

kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClusterService.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/ClusterServiceTest.java
Fixed topic offsets in topic list request
=> Provide topic offsets in list

kafka-ui-react-app/src/components/Version/Version.tsx, kafka-ui-react-app/src/components/Version/__tests__/compareVersions.spec.ts, kafka-ui-react-app/src/components/Version/compareVersions.ts, kafka-ui-react-app/src/lib/constants.ts
Implemented warning displaying for users who use outdated version of app.
=> #641 Warning that app version is outdated

kafka-ui-react-app/src/components/Version/__tests__/compareVersions.spec.ts
Removed tests for four-segment versions.
=> remove tests for four-segment version

kafka-ui-api/pom.xml, kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/schemaregistry/AvroMessageReader.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/schemaregistry/JsonSchemaMessageFormatter.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/schemaregistry/JsonSchemaMessageReader.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/schemaregistry/MessageFormat.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/schemaregistry/MessageReader.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/schemaregistry/ProtobufMessageReader.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/schemaregistry/SchemaRegistryAwareRecordSerDe.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/annotations/KafkaClientInternalsDependant.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/SendAndReadTests.java
=> Json Schema support 

kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/FullMessage.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessageContent.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessageItem.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Messages.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessagesTable.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/__test__/__snapshots__/MessageContent.spec.tsx.snap, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/__test__/__snapshots__/MessageItem.spec.tsx.snap, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/__test__/__snapshots__/MessagesTable.spec.tsx.snap
Refactoring of topic messages page
=> Fix topic messages

kafka-ui-api/src/main/java/com/provectus/kafka/ui/exception/TopicMetadataException.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaService.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/KafkaTopicCreateTests.java
=> Handle errors when creating topics and return as BAD_REQUEST

kafka-ui-react-app/src/components/ConsumerGroups/Details/Details.tsx, kafka-ui-react-app/src/components/ConsumerGroups/Details/__tests__/DetailsContainer.spec.tsx, kafka-ui-react-app/src/components/ConsumerGroups/List/List.tsx, kafka-ui-react-app/src/components/ConsumerGroups/List/__test__/List.spec.tsx, kafka-ui-react-app/src/components/ConsumerGroups/List/__test__/ListContainer.spec.tsx, kafka-ui-react-app/src/components/ConsumerGroups/List/__test__/ListItem.spec.tsx, kafka-ui-react-app/src/components/Schemas/Details/Details.tsx, kafka-ui-react-app/src/components/Schemas/Details/__test__/Details.spec.tsx, kafka-ui-react-app/src/components/Schemas/Details/__test__/__snapshots__/Details.spec.tsx.snap, kafka-ui-react-app/src/components/Topics/Topic/Details/ConsumerGroups/TopicConsumerGroups.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/ConsumerGroups/__test__/TopicConsumerGroups.spec.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessagesTable.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/__test__/MessagesTable.spec.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/__test__/__snapshots__/MessagesTable.spec.tsx.snap, kafka-ui-react-app/src/components/Topics/Topic/Details/Overview/Overview.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/Overview/__test__/Overview.spec.tsx
=> Review all tables and unify the way of data displaying. #602

README.md, guides/AWS_IAM.md, kafka-ui-api/pom.xml
=> #454 Added AWS IAM

.github/workflows/pr-checks.yaml
=> Fix pr checks job

kafka-ui-react-app/src/components/Topics/List/List.tsx, kafka-ui-react-app/src/components/Topics/List/ListItem.tsx, kafka-ui-react-app/src/components/Topics/List/__tests__/__snapshots__/List.spec.tsx.snap
=> Display replication factor field in topics list #608

docker/connectors/sink-activities.json, docker/connectors/source-activities.json, docker/connectors/start.sh, docker/kafka-ui-connectors.yaml, docker/postgres/Dockerfile, docker/postgres/data.sql
=> Create JDBC Source and Sink connectors from docker-compose

docker/kafka-connect/Dockerfile, docker/kafka-ui-connectors.yaml
=> [issue-698] Fix docker-compose with connectors

kafka-ui-react-app/src/components/Topics/Topic/Details/Overview/Overview.tsx
Added clean up policy to the topic overview:
=> Add clean up policy to the topic overview

kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/BrokersController.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/DescribeLogDirsMapper.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClusterService.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaService.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/LogDirsTest.java, kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
=> #707 Exposed broker log dirs

kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClustersStorage.java
=> Fix try for randomly failing tests (null in KafkaCluster.getTopics())

kafka-ui-react-app/src/components/Topics/List/List.tsx, kafka-ui-react-app/src/components/Topics/List/ListItem.tsx, kafka-ui-react-app/src/components/Topics/List/__tests__/__snapshots__/List.spec.tsx.snap, kafka-ui-react-app/src/components/Topics/Topic/Details/Overview/Overview.tsx
Added cleanup policy to the topic list
=> Display cleanup policy in the topic list

kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/BrokersController.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/ClusterMapper.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalBrokerConfig.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClusterService.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaService.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/ClusterUtil.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/KafkaConsumerTests.java, kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
I added endpoint for getting broker configs
=> Issue#701 brokers config

kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/BrokersController.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/exception/ErrorCode.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/exception/InvalidRequestApiException.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClusterService.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaService.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/ConfigTest.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/LogDirsTest.java, kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Added endpoint for broker config change
=> #702 Supported incremental config update for brokers

kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/ClusterMapper.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/schemaregistry/SchemaRegistryAwareRecordSerDe.java
Added checks in mapping schemaRegistry from properties
=> fix schemaRegistry property by adding checks

.github/workflows/backend.yml, .github/workflows/e2e-checks.yaml, kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/extensions/WaitUtils.java
=> Checks/498 extract e2e-checks from the main build 

docker/kafka-ui-traefik-proxy.yaml, docker/traefik/kafkaui.yaml
Was added docker compose file with an example of usage app in pair with traefik
should resolve #580 
=> Add example of docker-compose with Traefik proxy

kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/ClusterMapper.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalTopicConfig.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaService.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/ClusterUtil.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/KafkaConsumerTests.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/ClusterServiceTest.java, kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Added some new fields to Topic Configs.
New fields on TopicConfig
**How Has This Been Tested?**
**Checklist**
=> 703 additional fields topic config

guides/SASL_SCRAM.md
Adding SASL SCRAM Authentication to Guides
- [x ] Manually(please, describe, when necessary)
=> Creating SASL SCRAM AUTHENTICATION to Guides

charts/kafka-ui/templates/deployment.yaml
=> helm: add configmap and secret checksum

kafka-ui-react-app/src/components/Topics/List/List.tsx, kafka-ui-react-app/src/components/Topics/List/ListContainer.ts, kafka-ui-react-app/src/components/Topics/List/ListItem.tsx, kafka-ui-react-app/src/components/Topics/List/__tests__/List.spec.tsx, kafka-ui-react-app/src/components/Topics/List/__tests__/ListItem.spec.tsx, kafka-ui-react-app/src/components/Topics/List/__tests__/__snapshots__/List.spec.tsx.snap, kafka-ui-react-app/src/redux/actions/thunks/topics.ts
Implemented removing topics and topics messages using multi selection.
=> #243 #244 Delete topics and topics messages using multi-selection

kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/ClusterUtil.java
=> ISSUE-803 Backend fail if there is no version property

docker/kafka-ui-connectors.yaml
=> Fix kafka-ui image in kafka-ui-connectors.yaml

kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/CorsGlobalConfiguration.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClusterService.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClustersStorage.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaService.java, kafka-ui-api/src/main/resources/application-local.yml, kafka-ui-api/src/main/resources/application-sdp.yml
=> ISSUE-671 Fixed topic creation & deletion

kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/ClusterUtil.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/RecordEmitterTest.java
=> ISSUE-841 Fix null valued headers deserialisation

kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/ProtobufFileRecordSerDe.java
**What changes did you make?** Fixes issue #844 
=> #844: Do not remove newlines from the `.proto` file before parsing it.

docker/kafka-ui-connectors.yaml
=> Fix kafka-ui settings for Kafka Connect in kafka-ui-connectors.yaml

kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaService.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/MapUtil.java
=> ISSUE-856 Fixed failing on null topic partitions

kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/ConsumerGroupsController.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/OffsetsResetService.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/OffsetsResetServiceTest.java, kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
=> ISSUE-868 Fix group offsets reseting

kafka-ui-api/pom.xml, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/AvroJsonSchemaConverter.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/EnumJsonType.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/util/jsonschema/AvroJsonSchemaConverterTest.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/util/jsonschema/ProtobufSchemaConverterTest.java
=> ISSUE-876 Fixed avro json schema generation & deserializing

kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/AvroJsonSchemaConverter.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/ObjectFieldSchema.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/util/jsonschema/AvroJsonSchemaConverterTest.java
=> ISSUE-876 Fixed nullable fields

kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/AvroJsonSchemaConverter.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/ObjectFieldSchema.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/util/jsonschema/AvroJsonSchemaConverterTest.java
=> ISSUE-876 Fixed array types to oneof for js support

kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/ClusterMapper.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalSchemaRegistry.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/schemaregistry/SchemaRegistryAwareRecordSerDe.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/SchemaRegistryService.java
=> ISSUE-886 Schema registry multiple urls

docker/kafka-ui-auth-context.yaml, kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/Config.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/CorsGlobalConfiguration.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/CustomWebFilter.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/OAuthSecurityConfig.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/ReadOnlyModeFilter.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/AuthController.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/StaticController.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/EmptyRedirectStrategy.java
=> ISSUE-861 Context path fix

kafka-ui-contract/src/main/resources/swagger/kafka-connect-api.yaml
=> Fixed Stack Trace not showing up when connector fails

kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/CleanupPolicy.java
=> ISSUE-925 Added delete,compact topics config

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
=> Fix github templates label names

docker-compose.md
=> Fix environment typo

kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/BrokerServiceImpl.java
Fixed this:
```
{"code":5000,"message":"The broker does not support DESCRIBE_CONFIGS","timestamp":1633509870299,"requestId":"712f046f","fieldsErrors":null}
```
Might happen when using azure or old kafka brokers.
=> Fix unsupported DESCRIBE_CONFIGS

kafka-ui-react-app/src/components/Topics/List/List.tsx, kafka-ui-react-app/src/components/Topics/List/__tests__/__snapshots__/List.spec.tsx.snap
Fixed the issue with search and pagination.
=> Fix topics pagination

.github/workflows/welcome-first-time-contributors.yml
<h1>Pertains to #1058 </h1>
@Haarolean Can you please review this ?
=> Added a gh-action for the contributors

kafka-ui-react-app/src/components/Connect/New/New.tsx, kafka-ui-react-app/src/components/Connect/New/__tests__/New.spec.tsx, kafka-ui-react-app/src/components/Connect/New/__tests__/__snapshots__/New.spec.tsx.snap, kafka-ui-react-app/src/components/ConsumerGroups/Details/ResetOffsets/ResetOffsets.styled.ts, kafka-ui-react-app/src/components/ConsumerGroups/Details/ResetOffsets/ResetOffsets.tsx, kafka-ui-react-app/src/components/ConsumerGroups/Details/ResetOffsets/__test__/ResetOffsets.spec.tsx, kafka-ui-react-app/src/components/ConsumerGroups/Details/ResetOffsets/__test__/__snapshots__/ResetOffsets.spec.tsx.snap, kafka-ui-react-app/src/components/Schemas/New/New.tsx, kafka-ui-react-app/src/components/Schemas/New/__test__/New.spec.tsx, kafka-ui-react-app/src/components/Schemas/New/__test__/__snapshots__/New.spec.tsx.snap, kafka-ui-react-app/src/components/common/Textbox/Textarea.styled.ts
Redesigned some of the minor forms throughout the app:
=> Redesign some minor forms in the app

kafka-ui-react-app/src/components/Topics/shared/Form/TimeToRetainBtns.tsx
Fix 4w time to retain selector value. Closes #1060
=> Fix 4w time to retain selector value

kafka-ui-api/pom.xml, kafka-ui-api/src/main/resources/application.yml
Enable spring boot actuators including health and info
=> Enable spring boot actuators including health and info

.github/workflows/master.yaml, .github/workflows/release.yaml
Support of ARM platform was added to docker image build step
- [] I have added tests that prove my fix is effective or that my feature works
=> ENCH | Add ARM platform support for docker images

kafka-ui-e2e-checks/pom.xml, pom.xml
=> Fix jar hell

.github/workflows/master.yaml
This commit are changing:
- Stop auto-update in edu account
- Start updates in kafka-ui 
based on commits to master
=> Start use auto-updated deployment

pom.xml
Bump avro dependency. Closes #1084 
=> Bump avro dependency version

kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Changed type of field segmentSize from int to int64
=> #1106 Fixed segment size display on details page

.github/workflows/branch-deploy.yml, .github/workflows/branch-remove.yml, charts/kafka-ui/index.yaml
=> Workflows to deploy and remove custom env from branches 

.github/workflows/branch-deploy.yml, .github/workflows/branch-remove.yml
=> Fixes for custom build workflow

.github/workflows/branch-deploy.yml, .github/workflows/branch-remove.yml, .github/workflows/master.yaml
=> change_git_credentials_2shared_account

kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClustersMetricsScheduler.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClustersStorage.java
Add respect to cluster's order in ClustersStorage, changed map type to ImmutableMap to highlight its immutability
=> ISSUE-1128: Add respect to cluster's order in ClustersStorage

kafka-ui-react-app/.eslintrc.json, kafka-ui-react-app/package-lock.json, kafka-ui-react-app/package.json, kafka-ui-react-app/src/components/Alert/__tests__/Alert.spec.tsx, kafka-ui-react-app/src/components/ConsumerGroups/Details/ResetOffsets/__test__/ResetOffsets.spec.tsx, kafka-ui-react-app/src/components/ConsumerGroups/List/__test__/List.spec.tsx, kafka-ui-react-app/src/components/Dashboard/ClustersWidget/__test__/ClustersWidget.spec.tsx, kafka-ui-react-app/src/components/Topics/New/__tests__/New.spec.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessageContent/__tests__/MessageContent.spec.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/__test__/Message.spec.tsx, kafka-ui-react-app/src/components/Topics/Topic/Edit/__tests__/DangerZone.spec.tsx, kafka-ui-react-app/src/components/Topics/Topic/SendMessage/__test__/SendMessage.spec.tsx, kafka-ui-react-app/src/components/common/Breadcrumb/__tests__/Breadcrumb.spec.tsx
=> Refactor tests

kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/AdminClientServiceImpl.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/MetricsService.java
1. AdminClient error logging added
2. MetricsService error handling fixed
=> AdminClient creation error handling fix

pom.xml
Bump jackson-databind-nullable. Closes #1095
=> Bump jackson-databind-nullable

kafka-ui-react-app/src/components/Alert/Alert.styled.ts, kafka-ui-react-app/src/components/Alert/__tests__/Alert.spec.tsx, kafka-ui-react-app/src/components/Brokers/__test__/__snapshots__/Brokers.spec.tsx.snap, kafka-ui-react-app/src/components/Connect/List/__tests__/__snapshots__/ListItem.spec.tsx.snap, kafka-ui-react-app/src/components/ConsumerGroups/Details/ResetOffsets/__test__/ResetOffsets.spec.tsx, kafka-ui-react-app/src/components/ConsumerGroups/Details/__tests__/__snapshots__/Details.spec.tsx.snap, kafka-ui-react-app/src/components/ConsumerGroups/List/__test__/List.spec.tsx, kafka-ui-react-app/src/components/Dashboard/ClustersWidget/__test__/ClustersWidget.spec.tsx, kafka-ui-react-app/src/components/Nav/ClusterTab/__tests__/ClusterTab.spec.tsx, kafka-ui-react-app/src/components/Nav/__tests__/ClusterMenu.spec.tsx, kafka-ui-react-app/src/components/Nav/__tests__/ClusterMenuItem.spec.tsx, kafka-ui-react-app/src/components/Nav/__tests__/Nav.spec.tsx, kafka-ui-react-app/src/components/Schemas/New/__test__/__snapshots__/New.spec.tsx.snap, kafka-ui-react-app/src/components/Topics/New/__tests__/New.spec.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/Filters.spec.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessageContent/__tests__/MessageContent.spec.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/__test__/Message.spec.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/__test__/__snapshots__/Details.spec.tsx.snap, kafka-ui-react-app/src/components/Topics/Topic/Edit/__tests__/DangerZone.spec.tsx, kafka-ui-react-app/src/components/Topics/Topic/SendMessage/__test__/SendMessage.spec.tsx, kafka-ui-react-app/src/components/__tests__/App.spec.tsx, kafka-ui-react-app/src/components/common/Breadcrumb/__tests__/Breadcrumb.spec.tsx, kafka-ui-react-app/src/components/common/Input/__tests__/Input.spec.tsx, kafka-ui-react-app/src/components/common/PageLoader/__tests__/PageLoader.spec.tsx, kafka-ui-react-app/src/components/common/Select/__tests__/Select.spec.tsx, kafka-ui-react-app/src/lib/testHelpers.tsx, kafka-ui-react-app/src/redux/interfaces/alerts.ts, kafka-ui-react-app/src/theme/theme.ts
=> Add custom render with theme provider wrapper for testing lib

kafka-ui-react-app/openapitools.json, kafka-ui-react-app/package.json
Changed generator-cli version, added rimraf library for fix build on Windows
=> Changed generator-cli version, added rimraf library

guides/SSO.md
=> Update SSO guide

.github/dependabot.yml
=> Dependabot: support backend and github actiond

.github/workflows/branch-deploy.yml, .github/workflows/master.yaml
related to https://github.com/provectus/kafka-ui/issues/1143
=> provide github token to infra repo

kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml, kafka-ui-react-app/src/redux/reducers/topics/selectors.ts
Added cleanupPolicy to topic details. Closes #999
=> Added cleanupPolicy to topic details

charts/kafka-ui/templates/deployment.yaml
=> Fix image registry in helm chart

docker/kafka-ui-connectors.yaml, kafka-ui-api/pom.xml, kafka-ui-api/src/main/antlr4/ksql/KsqlGrammar.g4, kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/KsqlController.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/exception/ErrorCode.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/exception/KsqlApiException.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ksql/KsqlApiClient.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ksql/KsqlGrammar.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ksql/response/DynamicParser.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ksql/response/ResponseParser.java, kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml, pom.xml
New Ksql execution endpoint added.
Note: Haven't write tests since API can be changed when implementing UI, but I checked endpoint works manually
=> Ksql functionality reimplemented

.github/workflows/terraform-deploy.yml
add workflow for kafka-ui infra terraform deployment
Forked the repo and ran this workflow
=> terraform_deploy_workflow

charts/kafka-ui/values.yaml
=> add image registry param to values.yaml in kafka-ui chart

kafka-ui-react-app/src/components/Connect/List/List.tsx
=> Changed connect counter

.github/workflows/branch-deploy.yml
additionals for: https://github.com/provectus/kafka-ui/pull/1256 
=> use label name as trigger for public deployment

.github/workflows/branch-remove.yml
add support for new label for branch-remove.yml workflow
=> add support for new label for branch-remove.yml workflow

kafka-ui-react-app/package-lock.json
Reverts provectus/kafka-ui#1216
=> Revert "Bump history from 5.0.0 to 5.1.0 in /kafka-ui-react-app"

kafka-ui-api/Dockerfile
Changed base FROM image for our docker image to use alpine and added one layer to install openjdk-13-jre.
Closes https://github.com/provectus/kafka-ui/issues/986
=> Add possibility to run kafka-ui container on ARM64

.github/workflows/terraform-deploy.yml
=> Use kafka-ui-infra token in terraform deploy workflow.

.github/workflows/e2e-checks.yaml
=> Bump github-status-action

.github/workflows/terraform-deploy.yml
=> add possibility to run tf from branch

kafka-ui-react-app/package-lock.json, kafka-ui-react-app/src/components/Schemas/List/GlobalSchemaSelector/GlobalSchemaSelector.tsx, kafka-ui-react-app/src/redux/actions/__test__/thunks/schemas.spec.ts, kafka-ui-react-app/src/redux/actions/thunks/schemas.ts
=> [ISSUE-1210] Change of the Global Comp Level updates the list of schemas

kafka-ui-react-app/src/components/ConsumerGroups/Details/ResetOffsets/ResetOffsets.tsx
=> Disabled negative values.

kafka-ui-api/src/main/resources/application.yml
=> Fix healthchecks

charts/kafka-ui/templates/ingress.yaml
Closes https://github.com/provectus/kafka-ui/issues/1337
=> Update ingress.yaml in kafka-ui chart to support kubernetes 1.22+

kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/schemaregistry/SchemaRegistryAwareRecordSerDe.java
=> Fix NPE on producing a message

charts/kafka-ui/templates/ingress.yaml
Enhancements to support new k8s api version
=> enhancement to support ingress api 1.22+

kafka-ui-api/Dockerfile
libc6 & gcompat libs added to docker image to support all kafka compression codecs
=> ISSUE-1347: system libs added to Dockerfile to support all compressions

kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalTopic.java
bytesOutPerSec metric added to topic
=> bytesOutPerSec metric added to topic

guides/SSO.md
Hello, thank you for creating and maintaining this great product.
I've updated SSO guide to include Azure AD setup, which I've struggled with a bit.
=> Example for Azure AD setup

kafka-ui-react-app/src/components/Topics/Topic/Details/Details.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/__test__/Details.spec.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/__test__/__snapshots__/Details.spec.tsx.snap
=> Added a popup warning about deleting topic messages.

charts/kafka-ui/templates/ingress.yaml, charts/kafka-ui/values.yaml
Support for ingressClassName in helm chart added
=> Support for ingressClassName in helm chart

kafka-ui-react-app/src/components/Brokers/Brokers.tsx, kafka-ui-react-app/src/components/Connect/Details/Overview/Overview.tsx, kafka-ui-react-app/src/components/Connect/Details/Overview/__tests__/__snapshots__/Overview.spec.tsx.snap, kafka-ui-react-app/src/components/Connect/Details/Tasks/ListItem/ListItem.tsx, kafka-ui-react-app/src/components/Connect/Details/Tasks/ListItem/__tests__/__snapshots__/ListItem.spec.tsx.snap, kafka-ui-react-app/src/components/Connect/List/ListItem.tsx, kafka-ui-react-app/src/components/Connect/List/__tests__/__snapshots__/ListItem.spec.tsx.snap, kafka-ui-react-app/src/components/ConsumerGroups/Details/Details.tsx, kafka-ui-react-app/src/components/ConsumerGroups/List/ListItem.tsx, kafka-ui-react-app/src/components/Dashboard/ClustersWidget/ClustersWidget.tsx, kafka-ui-react-app/src/components/Topics/List/ListItem.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/ConsumerGroups/TopicConsumerGroups.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/Overview/Overview.tsx, kafka-ui-react-app/src/components/Topics/shared/Form/TopicForm.styled.ts, kafka-ui-react-app/src/components/common/Tag/Tag.styled.tsx
=> Empty table for brokers & chnge tag styles

kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/ConsumerGroupsController.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/ConsumerGroupMapper.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalConsumerGroup.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ConsumerGroupService.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ReactiveAdminClient.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/ClusterUtil.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/KafkaConsumerGroupTests.java, kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
* consumer-groups endpoint with pagination added
* consumer group dto mappings moved to controller
* consumer groups loading logic refactored
=> Consumer groups pagination (Backend)

kafka-ui-react-app/src/components/Schemas/List/GlobalSchemaSelector/GlobalSchemaSelector.tsx, kafka-ui-react-app/src/components/Schemas/List/GlobalSchemaSelector/__test__/GlobalSchemaSelector.spec.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/__snapshots__/Filters.spec.tsx.snap, kafka-ui-react-app/src/components/common/Select/Select.tsx
=> Added GlobalSchemaSelector tests

.github/workflows/separate_env_public_create.yml, .github/workflows/separate_env_public_remove.yml
resolves https://github.com/provectus/kafka-ui/issues/1310
=> Implement a workflow to create separate environment

kafka-ui-react-app/package-lock.json
Reverts provectus/kafka-ui#1379
=> Revert "Bump follow-redirects from 1.14.5 to 1.14.7 in /kafka-ui-react-app"

kafka-ui-react-app/src/components/Connect/Details/Tasks/__tests__/__snapshots__/Tasks.spec.tsx.snap, kafka-ui-react-app/src/components/Connect/List/__tests__/__snapshots__/ListItem.spec.tsx.snap, kafka-ui-react-app/src/components/Topics/List/List.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/__test__/__snapshots__/Details.spec.tsx.snap, kafka-ui-react-app/src/components/common/table/TableHeaderCell/TableHeaderCell.styled.ts, kafka-ui-react-app/src/components/common/table/TableHeaderCell/TableHeaderCell.tsx, kafka-ui-react-app/src/components/common/table/__tests__/TableHeaderCell.spec.tsx, kafka-ui-react-app/src/redux/reducers/topics/reducer.ts, kafka-ui-react-app/src/theme/theme.ts
- Now Topics has default sorting (by name)
- Current sorting is highlighted (if `orderValue` exists and `orderBy===orderValue`)
- If `TableHeaderCell` is sortable - title will be rendered with sort icon and highlighted on hover
- Updated snapshots 
1) I don't like [line 33 in `TableHeaderCell.tsx`](https://github.com/Motherships/kafka-ui/blob/4a07c15cd9bcc4b162ada2020131d4a2aeb5a242/kafka-ui-react-app/src/components/common/table/TableHeaderCell/TableHeaderCell.tsx#L33), I had to double check `orderValue && handleOrderBy` so TS compiled successfully, but I would like to use `isSortable` to check if `<S.Title>` needed extra props
2) I'm not sure if [line 48 is correct in file …
=> [Fixes #1212] Confusing sorting UI in Topics

kafka-ui-api/Dockerfile
To prevent unnecessary anonymous volumes creation (on each container start we currently create anonymous volume that will **not** be deleted after container stop)
=> tmp volume declaration removed 

kafka-ui-react-app/src/theme/index.scss
=> Prepare bulma for removal

.github/workflows/backend.yml, .github/workflows/documentation.yaml, .github/workflows/e2e-checks.yaml, .github/workflows/frontend.yaml, kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/SmokeTests.java, kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/ConnectorsTests.java, kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/TopicTests.java
resolves: https://github.com/provectus/kafka-ui/issues/1447
To make it work set required check build-and-test in repo branch settings.
=> required PR checks workflows adaptation

.github/workflows/branch-deploy.yml
=> Specify time period in which custom deployment will be available

.github/workflows/codeql-analysis.yml
=> Limit codeql run by frontend paths

.github/workflows/release.yaml
tested in a forked repo.
resolves: https://github.com/provectus/kafka-ui/issues/1504
=> Add step to attach built jar to a release

kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalClusterState.java
Added missing readonly fields when converting cluster props
=> Add missing readonly field

kafka-ui-react-app/src/components/Connect/List/__tests__/__snapshots__/ListItem.spec.tsx.snap, kafka-ui-react-app/src/components/Topics/Topic/Details/__test__/__snapshots__/Details.spec.tsx.snap, kafka-ui-react-app/src/components/common/Select/Select.styled.ts, kafka-ui-react-app/src/theme/theme.ts
- Fixes #1520 
- Updates `Select` component to always show scrollbar (custom one) on webkit browsers
The color or scrollbar style can be discussed 
=> [Fixes #1520] Too short visible list for Schema compatibility level selector 

kafka-ui-react-app/src/components/common/table/TableHeaderCell/TableHeaderCell.styled.ts
A little bugfix Code Smells from SonarCloud tests 
=> fixed Code Smells from PR 1494

kafka-ui-react-app/src/components/common/Select/Select.styled.ts
Increased height visible list in Select-dropdown selector
Remove horizontal scrollbar
=> [ISSUE-1533] Update visible list in dropdown selector

.github/workflows/branch-deploy.yml, .github/workflows/master.yaml, .github/workflows/release.yaml, kafka-ui-api/pom.xml, kafka-ui-contract/pom.xml, kafka-ui-e2e-checks/pom.xml, pom.xml
Use maven versions:set instead of custom variables in pom files in CI/CD.
fixes: https://github.com/provectus/kafka-ui/issues/1558
=> Fix maven warnings about dynamic versioning

kafka-ui-react-app/src/components/Connect/Details/Config/Config.tsx, kafka-ui-react-app/src/components/Connect/Details/Config/__test__/__snapshots__/Config.spec.tsx.snap, kafka-ui-react-app/src/components/common/Editor/Editor.tsx
Made adaptive height in JSON-editor in connectors config
Remove wrapper-styles to make it look like figma's design
=> [Issue-1490] Made adaptive height in connectors config component

.github/workflows/backend.yml, .github/workflows/e2e-checks.yaml, .github/workflows/frontend.yaml
Resolves: https://github.com/provectus/kafka-ui/issues/1009
Additionaly set mvn build versions for backend frontend and e2e workflows.
=> Allow running sonar within PR of a fork

.github/workflows/documentation.yaml
Resolves: https://github.com/provectus/kafka-ui/issues/1606
=> Fix workflow for documentation

.github/workflows/aws_publisher.yaml
This workflow build AWS AMI with installed UI with specified version.
It is not affect any existing workflows, it could be triggered only manually.
=> build ami workflow for aws marketplace

kafka-ui-react-app/src/lib/hooks/__tests__/useDataSaver.spec.tsx, kafka-ui-react-app/src/lib/hooks/useDataSaver.ts
Edited copyToClipboard function, also updated linked test.
Pay your attention on this function, which get 'data' as a string and try to make additional JSON.stringify() from String. It caused this bug
=> [FIXED issue/1544] Resolved bug with export of JSON message to clipboard/file

kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaConnectService.java, kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
RESTART_ALL_TASKS & RESTART_FAILED_TASKS actions implemented, small refactoring
=> ISSUE-1444: Connect RESTART_ALL_TASKS & RESTART_FAILED_TASKS 

.github/workflows/backend.yml, .github/workflows/e2e-checks.yaml
Resolves: https://github.com/provectus/kafka-ui/issues/1625
=> Trigger backend workflow on root pom.xml change

charts/kafka-ui/templates/ingress.yaml
=> Template ingress hostname

kafka-ui-react-app/src/components/Brokers/Brokers.tsx, kafka-ui-react-app/src/components/Schemas/Diff/DiffContainer.ts, kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx
=> Quickfix warning

kafka-ui-react-app/src/components/Topics/Topic/Details/Overview/Overview.tsx
=> Rename offsets columns and add "message count" in topic details page

kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/MetricsCache.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/MetricsService.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/BrokerServiceTest.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/TopicsServicePaginationTest.java, kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
* initializing status added to cluster
* MetricsCache initializing
* unuseful tests removed BrokerServiceTest
=> "initializing" state added to ServerStatus enum

.github/workflows/cve.yaml
Resolves: https://github.com/provectus/kafka-ui/issues/1661
Runs on schedule every 15th day of month.
Can be triggered manually.
=> Add cve checks wf

kafka-ui-api/src/test/java/com/provectus/kafka/ui/AbstractIntegrationTest.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/KafkaConnectServiceTests.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/KafkaConsumerGroupTests.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/KafkaConsumerTests.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/KafkaTopicCreateTests.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/ReadOnlyModeTests.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/SchemaRegistryServiceTests.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/emitter/TailingEmitterTest.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/BrokerServiceTest.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/ConfigTest.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/LogDirsTest.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/MessagesServiceTest.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/OffsetsResetServiceTest.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/RecordEmitterTest.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/SendAndReadTests.java, kafka-ui-api/src/test/resources/application-test.yml
Integration tests structure unified, unnecessary imports removed
=> Integration tests minor improvements

kafka-ui-react-app/src/components/Topics/Topic/Details/Settings/__test__/Settings.spec.tsx
**What changes did you make?
Writing a Test File for Settings Component to cover the weakness that was mentioned in the Sonar.
=> Adding Test File for Settings Component

kafka-ui-react-app/src/components/ConsumerGroups/Details/ListItem.tsx, kafka-ui-react-app/src/components/ConsumerGroups/Details/TopicContents/__test__/TopicContent.spec.tsx, kafka-ui-react-app/src/components/ConsumerGroups/Details/TopicContents/__test__/TopicContents.spec.tsx, kafka-ui-react-app/src/components/ConsumerGroups/Details/__tests__/ListItem.spec.tsx, kafka-ui-react-app/src/components/ConsumerGroups/List/__test__/List.spec.tsx, kafka-ui-react-app/src/components/ConsumerGroups/__test__/ConsumerGroups.spec.tsx
Issue 1650: improving test cases for ConsumerGroups components
* Unit tests coverage
=> Issue 1650: improving test cases for ConsumerGroups components

kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ConsumerGroupService.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/TopicsService.java
* load topic after creation retry added
* TopicService.recreateTopic,cloneTopic formatting improved
* ALLOW_AUTO_CREATE_TOPICS_CONFIG set to false for all created consumer to avoid accidental topic creation
=> ISSUE-1613: Fix Topic not found error after new topic creation

kafka-ui-react-app/src/components/Topics/New/__test__/New.spec.tsx, kafka-ui-react-app/src/components/Topics/shared/Form/TopicForm.tsx, kafka-ui-react-app/src/components/Topics/shared/Form/__tests__/TopicForm.spec.tsx
=> Rename 'send' button to 'submit'

kafka-ui-react-app/src/components/Nav/ClusterTab/ClusterTab.styled.ts, kafka-ui-react-app/src/components/Nav/ClusterTab/__tests__/ClusterTab.styled.spec.tsx, kafka-ui-react-app/src/theme/theme.ts
=> Clusters Style change during initializing phase + implement tests suites

kafka-ui-react-app/src/components/Brokers/Brokers.tsx, kafka-ui-react-app/src/redux/actions/__test__/fixtures.ts, kafka-ui-react-app/src/redux/interfaces/broker.ts, kafka-ui-react-app/src/redux/reducers/brokers/__test__/fixtures.ts, kafka-ui-react-app/src/redux/reducers/brokers/__test__/selectors.spec.ts, kafka-ui-react-app/src/redux/reducers/brokers/brokersSlice.ts, kafka-ui-react-app/src/redux/reducers/brokers/selectors.ts
=> Get Rid of Zookeeper

kafka-ui-react-app/package-lock.json, kafka-ui-react-app/package.json
=> Add rimraf in dev-dependencies and remove from dependencies

kafka-ui-react-app/src/components/Connect/Details/Actions/Actions.tsx, kafka-ui-react-app/src/components/Connect/Details/Actions/ActionsContainer.ts, kafka-ui-react-app/src/components/Connect/Details/Actions/__tests__/Actions.spec.tsx, kafka-ui-react-app/src/components/Connect/Details/Actions/__tests__/__snapshots__/Actions.spec.tsx.snap, kafka-ui-react-app/src/redux/actions/__test__/thunks/connectors.spec.ts, kafka-ui-react-app/src/redux/actions/actions.ts, kafka-ui-react-app/src/redux/actions/thunks/connectors.ts
=> Frontend: Restart connectors buttons

kafka-ui-react-app/src/components/Topics/List/List.tsx, kafka-ui-react-app/src/components/common/SmartTable/TableColumn.tsx, kafka-ui-react-app/src/components/common/SmartTable/TableRow.tsx, kafka-ui-react-app/src/components/common/table/TableHeaderCell/TableHeaderCell.styled.ts
I added maxWidth to the table cell and some styles for text wrapping
Maybe we should add tooltip to the topic labels?
=> Added maxWidth to the table row styles

kafka-ui-react-app/src/components/Topics/List/List.tsx, kafka-ui-react-app/src/components/Topics/List/__tests__/List.spec.tsx
=> Fix page reset after search in topics list

README.md
Disclaimer was added at the request of @germanosin
=> Add a disclaimer

kafka-ui-react-app/sonar-project.properties
Updates `sonar.exclusions` list
=> exclude serviceWorker file from sonar's list

kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ReactiveAdminClient.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/JmxClusterUtil.java
* jmx metrics collection parallelized on elastic scheduler
* explicitly setting publishing Scheduler for KafkaFuture-based Monos
=> Fixing AdminClients requesting stucking

kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Message.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessageContent/MessageContent.styled.ts, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessageContent/MessageContent.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessagesTable.tsx
=> Remove unnecessary links and texts in topic messages

kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.tsx
I added clearing offset functionality to the rest of related code.
=> Added clearing offset

kafka-ui-react-app/src/components/Topics/List/List.styled.ts, kafka-ui-react-app/src/components/Topics/List/List.tsx, kafka-ui-react-app/src/components/common/SmartTable/TableColumn.tsx, kafka-ui-react-app/src/components/common/SmartTable/TableRow.tsx
I added style attribute to the custom smart table column component. The className that was previously assigned, didn't work at all, so I removed it. Made the overflow visible on that specific td to make it visible. 
Instead of writing inline classes it would be nice to use styled components, but because of the current implemented structure, styled components didn't work, I couldn't find a better way to fix it. …
=> Fix topic list invisible actions menu

kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/CustomWebFilter.java
=> Fix empty base path when forwarding to index page

kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/SchemaRegistryService.java
=> Fix schema name nullability on compatibility change

kafka-ui-react-app/src/components/common/Breadcrumb/Breadcrumb.tsx, kafka-ui-react-app/src/lib/__test__/paths.spec.ts, kafka-ui-react-app/src/lib/constants.ts, kafka-ui-react-app/src/lib/paths.ts
added new variable in constants which can be used to keep breadcrumb definitions which are different from our standarts
=> Change spelling of ksqlDB at bread crumbs

kafka-ui-react-app/src/components/KsqlDb/List/ListItem.tsx
I removed hardcoded string and its dropdown because of currently in development content and functionality
https://4.404content.com/1/FD/82/877480125544793366/fullsize.jpg
=> Hardcoded string with dropdown removed

kafka-ui-react-app/src/components/KsqlDb/Query/Query.tsx
I deleted the code that caused closing alert message
=> Auto-closing of alert message removed

kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.tsx
=> Fix topic messages offset filter bug

kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/CustomParamField.tsx, kafka-ui-react-app/src/components/common/Select/Select.styled.ts, kafka-ui-react-app/src/components/common/Select/Select.tsx, kafka-ui-react-app/src/components/common/Select/__tests__/Select.spec.tsx
Updated the functionality to fix the bug, added the proper styles for displaying disabled options, and updated the tests.
=> Fix topic custom parameter duplication overriding

kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessagesTable.tsx
Change offset to offset + 1 when seek direction is FORWARD.
=> Fix double topic message display bug

kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/__test__/Messages.spec.tsx
https://user-images.githubusercontent.com/103444767/164410459-b2e97aef-d517-4022-b880-ba6a40401334.mov
=> Remove offset input render condition in topic messages filters

kafka-ui-react-app/src/components/Topics/List/List.styled.ts, kafka-ui-react-app/src/components/Topics/List/List.tsx
Gave the dropdown 'td' fixed width to prevent width change on mouseover. Visibility hidden is not a good solution because that way the dropdown's isOpen state will persist (I've tried that).
=> Fix dropdown jump effect bug on mouse over in topics list

kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessageContent/MessageContent.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessageContent/__tests__/MessageContent.spec.tsx
=> fixing timestamp type for message content

kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.tsx
=> Add Debounce to the Topics Filters search component

kafka-ui-react-app/src/components/Topics/Topic/Details/Overview/__test__/Overview.spec.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/__test__/Details.spec.tsx
Achieved 100% coverage on the following components:
1. src/components/Topics/Topic/Details/Details.tsx
2. src/components/Topics/Topic/Details/Overview/Overview.tsx
=> Improve tests coverage

kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/AddFilter.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.styled.ts, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/__tests__/AddFilter.spec.tsx
1. Made smart filter items prettier.
2. Used the beginning of the code with '...' at the end as the filter name if name field is empty.
3. Covered my changes with tests.
4. Added test cases for Edit Saved Filter feature to achieve 100% coverage.
**Screenshot**
=> Smart filter improvements

kafka-ui-react-app/README.md
Updated Readme with correct sonarCloud badges
=> Fix sonar badges in readme

kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.tsx
=> Fix topic messages partitions filter bug

kafka-ui-api/pom.xml
No, breaking change. 
Update the dependency of `aws-msk-iam` due to security issues. This dependency fixed the well known `log4j` issue in the previous version.
Due to limitations of the tests, I couldn't run them on macOS. Please make sure all tests are passing.
- Build and run container image on my local machine.
=> Security / chore(dep): upgrade aws-msk-iam dependency due to log4j vulnerability

kafka-ui-api/pom.xml
Added jacoco reports to sonar
Check is Sonar correctly shows coverage
Tested on fork  (https://sonarcloud.io/summary/overall?id=com.provectus%3Akafka-ui)
=> Configure jacoco reports to sonar

kafka-ui-react-app/src/components/common/Metrics/Metrics.styled.tsx
- [] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)
I fixed border radius so the Metric container now is with rounded corners
Rounded corners added to the whole metrics section
=> Border radius fixed

kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.tsx
=> Edit messages consumed text

kafka-ui-react-app/src/components/Connect/List/List.tsx
Signed-off-by: doomcrewinc <oilfield101@gmail.com>
Replaced `Connects` with `Connectors` on the Dashboard, to reflect Issue:2037 changes.
=> issues/2037: Changed 'Connects' to 'Connectors'

kafka-ui-api/pom.xml, kafka-ui-contract/pom.xml, pom.xml
=> Fix version display

kafka-ui-react-app/src/components/common/MultiSelect/MultiSelect.styled.ts
=> Show close icon on hover

kafka-ui-react-app/src/components/Topics/Topic/Details/Overview/Overview.tsx, kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx, kafka-ui-react-app/src/redux/reducers/topicMessages/topicMessagesSlice.ts
The problem was not only when we cleared messages but also when we add new messages. I fixed it for both cases.
Adding new message needs improvement but let's keep it like this for now. I will refactor that with separate PR when have time. 
=> The result of Clear Messages is not displayed in Topic overview

kafka-ui-react-app/src/components/common/Icons/DropdownArrowIcon.tsx, kafka-ui-react-app/src/components/common/Select/Select.styled.ts, kafka-ui-react-app/src/components/common/Select/Select.tsx, kafka-ui-react-app/src/theme/theme.ts
=> fixing dropdown arrow behavior for Topics Messages

kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessagesTable.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/__test__/MessagesTable.spec.tsx, kafka-ui-react-app/src/components/Version/Version.tsx, kafka-ui-react-app/src/lib/constants.ts
I removed Next button from the messages table.
=> Next button removed

kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/utils.ts, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/__test__/utils.spec.ts
Fixed Selected partitions label on the Topics overview page on Messages tab
=> Fixed Selected partitions label

kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx
=> adding error message when created message has wrong header format

kafka-ui-react-app/src/components/Topics/New/New.tsx, kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/CustomParamField.tsx, kafka-ui-react-app/src/lib/yupExtended.ts
=> Error message about Value field requiredness is shown once the Custom Parameter added within Create a new Topic form

kafka-ui-react-app/src/components/Topics/Topic/Details/Details.tsx
=> disable produce message button if cluster is readOnly

kafka-ui-react-app/package-lock.json, kafka-ui-react-app/package.json
=> Remove History from packages

kafka-ui-react-app/src/components/Topics/New/New.tsx, kafka-ui-react-app/src/lib/constants.ts, kafka-ui-react-app/src/redux/interfaces/loader.ts, kafka-ui-react-app/src/redux/reducers/clusters/clustersSlice.ts, kafka-ui-react-app/src/redux/reducers/connect/selectors.ts, kafka-ui-react-app/src/redux/reducers/consumerGroups/consumerGroupsSlice.ts, kafka-ui-react-app/src/redux/reducers/ksqlDb/selectors.ts, kafka-ui-react-app/src/redux/reducers/loader/loaderSlice.ts, kafka-ui-react-app/src/redux/reducers/loader/selectors.ts, kafka-ui-react-app/src/redux/reducers/schemas/schemasSlice.ts, kafka-ui-react-app/src/redux/reducers/topics/selectors.ts
=> Adding AsyncRequestStatus enum to avoid possible gramatical issues

kafka-ui-react-app/src/redux/reducers/topics/__test__/reducer.spec.ts, kafka-ui-react-app/src/redux/reducers/topics/topicsSlice.ts
=> Adding success alert message for topic deletion

charts/kafka-ui/Chart.yaml
=> Fix helm icon URL

kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/BasicAuthSecurityConfig.java
Logout filters have been de-configured automatically due to specifying custom `loginPage`. So I explicitly configured them.
`httpBasic` has been removed since it doesn't support logout at all.
=> Fix basic auth logout page

kafka-ui-react-app/src/components/Schemas/Details/Details.tsx, kafka-ui-react-app/src/components/Schemas/Schemas.tsx
=> Fixing schema version compare version path issue

kafka-ui-react-app/src/components/KsqlDb/List/List.tsx, kafka-ui-react-app/src/components/KsqlDb/List/ListItem.tsx, kafka-ui-react-app/src/components/KsqlDb/List/__test__/ListItem.spec.tsx, kafka-ui-react-app/src/redux/interfaces/ksqlDb.ts, kafka-ui-react-app/src/redux/reducers/ksqlDb/ksqlDbSlice.ts
=> Using new API endpoint for KSQLDB instead of deprecated one

kafka-ui-react-app/src/components/Cluster/Cluster.tsx
=> Import Brokers page without lazy

kafka-ui-react-app/src/components/KsqlDb/List/List.tsx, kafka-ui-react-app/src/components/KsqlDb/List/ListItem.tsx, kafka-ui-react-app/src/components/KsqlDb/Query/renderer/TableRenderer/TableRenderer.tsx
=> Adding isWindowed column to ksql table

.github/workflows/backend.yml
=> Fix possible CWE-94

kafka-ui-react-app/src/components/Schemas/Edit/Edit.tsx
=> Fixing compatibility and schema update order

.github/workflows/branch-remove.yml
=> Do not add comments if label was not set

kafka-ui-react-app/src/components/Brokers/Broker/Broker.tsx, kafka-ui-react-app/src/components/Brokers/Broker/__test__/Broker.spec.tsx
=> Update logdir label

README.md
=> docs: Fix typo in JMXPORT description

kafka-ui-react-app/src/components/Schemas/New/New.tsx, kafka-ui-react-app/src/components/Topics/List/ActionsCell/ActionsCell.tsx
=> fixing create schema page validation issue

.github/workflows/helm.yaml, charts/kafka-ui/templates/ingress.yaml
The changes in this PR aims to fix this issue https://github.com/provectus/kafka-ui/issues/2317
=> Fixed ingress template for k8s version older than 1.19

kafka-ui-react-app/src/components/KsqlDb/Query/QueryForm/QueryForm.styled.ts
=> remove ksql editor unnecessary line

documentation/compose/kafka-ui-connectors-auth.yaml
=> fix kafka-connect healthcheck probe

kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/TopicTests.java
=> Disable unstable topic test

kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx, kafka-ui-react-app/src/components/common/Alert/Alert.styled.ts, kafka-ui-react-app/src/components/common/Alert/Alert.tsx, kafka-ui-react-app/src/lib/errorHandling.tsx
=> Update Alerts to use ReactNode as a message content

charts/kafka-ui/Chart.yaml, charts/kafka-ui/templates/ingress.yaml
This PR should solve this [issue](https://github.com/provectus/kafka-ui/issues/2382)
=> Use semver object to check version compatability in HELM Chart #2385

kafka-ui-react-app/src/components/Topics/New/__test__/New.spec.tsx, kafka-ui-react-app/src/lib/constants.ts, kafka-ui-react-app/src/lib/yupExtended.ts
=> Fix validation message for Topic name field

kafka-ui-react-app/src/components/Topics/Topic/Details/Statistics/Indicators/Total.tsx
=> Fix "unique" labels abbreviations

documentation/project/contributing/building.md, kafka-ui-api/pom.xml
Fixes #1666 
Added skip property to avoid running the FE plugin and its build if needed.
=> Request: a command to compile just kafka-ui-api, ignoring the frontend #1666

kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/MainPage.java, kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/Pages.java, kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/ProduceMessagePage.java, kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/connector/ConnectorsList.java, kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaCreateView.java, kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaEditView.java, kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaRegistryList.java, kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaView.java, kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicCreateEditSettingsView.java, kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicView.java, kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicsList.java
=> verify Step annotation cross page methods.

kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/base/BaseTest.java
=> Fix e2e tests stability

kafka-ui-api/Dockerfile
=> Fix transient jre CVEs

kafka-ui-react-app/src/components/Topics/shared/Form/TopicForm.tsx
Redirect to topics page
closes #2392
=> Redirect to topics page #2392

kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/SchemaRegistryService.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/SchemaRegistryServiceTests.java
Use build instead of buildAndExpand to fix paths
Add Test for subject name with non ascii chars
Closes #1995
=> Fix URL encoding while getting schemas 

.github/workflows/documentation.yaml, kafka-ui-react-app/src/components/Schemas/Details/__test__/Details.spec.tsx, kafka-ui-react-app/src/components/Schemas/Details/__test__/fixtures.ts, kafka-ui-react-app/src/components/Schemas/Edit/__tests__/Edit.spec.tsx, kafka-ui-react-app/src/components/Schemas/List/__test__/fixtures.ts, kafka-ui-react-app/src/lib/__test__/paths.spec.ts, kafka-ui-react-app/src/lib/paths.ts, kafka-ui-react-app/src/redux/reducers/schemas/__test__/fixtures.ts
Fix subject encoding frontend for Edit and Details Schema Page (#1995)
Closes #1995
=> Fix subject encoding frontend (#1995)

documentation/compose/DOCKER_COMPOSE.md, documentation/compose/kafka-ui-arm64.yaml, documentation/compose/scripts/update_run.sh
Add arm64 kafka-ui docker compose script
closes #2502
Reference Taken from : https://github.com/confluentinc/cp-all-in-one/blob/7.0.5-post/cp-all-in-one-kraft/docker-compose.yml
=> Add arm64 kafka-ui docker compose script

kafka-ui-react-app/src/components/Topics/Topic/Messages/Message.tsx, kafka-ui-react-app/src/lib/hooks/__tests__/useDataSaver.spec.tsx, kafka-ui-react-app/src/lib/hooks/useDataSaver.ts
Add full message details 
Closes #2365
=> Add full message details to export

index.yaml
=> fix appVersion version

charts/kafka-ui/templates/deployment.yaml
Reverts provectus/kafka-ui#2548
=> Revert "add labels required by istio"

kafka-ui-api/pom.xml, pom.xml
Replacing spotify maven docker plugin to use fabric8 docker maven plugin instead
=> Get rid of dockerfile-maven-plugin

kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/connector/ConnectorsView.java, kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaView.java, kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicView.java, kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicsList.java, kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/TopicTests.java, kafka-ui-react-app/src/components/Brokers/BrokersList/BrokersList.tsx
=> [e2e] fix tests on master

.github/workflows/e2e-checks.yaml, kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/connector/ConnectorsView.java, kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/schema/SchemaView.java, kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicView.java, kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicsList.java, kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/base/BaseTest.java, kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/TopicTests.java
=> Build local image upon e2e

documentation/project/contributing/building-and-running-without-docker.md, documentation/project/contributing/building.md
Update docs to reflect changes regarding building docker images:
1) building images is fixed on m1/arm
2) updated plugin name in dockerless docs
@shubhwip @JIBIN-P FYI
=> Update docs on docker plugin

kafka-ui-react-app/src/components/Schemas/Details/LatestVersion/LatestVersionItem.tsx, kafka-ui-react-app/src/components/Schemas/Details/__test__/LatestVersionItem.spec.tsx
Replaced Relevant with Actualon the Registry Schema, to reflect Issue:2533 changes.
=> Rename "Relevant" version of a schema to "Actual"

kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/SavedFilters.tsx, kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/__tests__/SavedFilters.spec.tsx
Change the "Back to custom filters" link text within Saved filters
=> Change the "Back to custom filters" link text within Saved filters

kafka-ui-react-app/src/components/ConsumerGroups/Details/Details.tsx
Add "Total lag" within Consumer group
=> Add "Total lag" within Consumer group (#2530)

kafka-ui-api/pom.xml, kafka-ui-api/src/main/java/com/provectus/kafka/ui/KafkaUiApplication.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/LdapSecurityConfig.java, kafka-ui-api/src/main/resources/application.yml
=> Disable ldap beans auto configuration

kafka-ui-react-app/src/components/Topics/Topic/ConsumerGroups/TopicConsumerGroups.tsx
Add "Num of Topics" to Topic/Consumer tab
=> Add "Num of Topics" to Topic/Consumer tab (#2537)

kafka-ui-react-app/src/components/Schemas/Details/Details.tsx, kafka-ui-react-app/src/components/Schemas/Details/LatestVersion/LatestVersionItem.tsx, kafka-ui-react-app/src/components/Schemas/Details/SchemaVersion/SchemaVersion.tsx, kafka-ui-react-app/src/components/Schemas/Details/__test__/SchemaVersion.spec.tsx, kafka-ui-react-app/src/components/Schemas/List/List.tsx, kafka-ui-react-app/src/components/Schemas/List/__test__/List.spec.tsx
=> Display additional fields in the table and overview

README.md
Typo in Disclaimer for "enterprise":
<em>UI for Apache Kafka is a free tool built and supported by the open-source community. Curated by Provectus, it will remain free and open-source, without any paid features or subscription plans to be added in the future. Looking for the help of Kafka experts? Provectus can help you design, build, deploy, and manage Apache Kafka clusters and streaming applications. Discover [Professional Services for Apache Kafka](https://provectus.com/professional-services-apache-kafka/), to unlock the full potential of Kafka in your **enterprise**! </em>
**Checklist** (put an "x" …
=> Update typo in "Enterprise" on root Readme.md

kafka-ui-react-app/src/components/Schemas/Details/SchemaVersion/SchemaVersion.tsx
Schema registry: Previous version's schema preview is too narrow
=> Schema registry: Previous version's schema preview is too narrow

kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/base/BaseTest.java, kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/base/Setup.java
=> Issue_2438

kafka-ui-api/pom.xml
=> Expose build info for actuator

kafka-ui-react-app/src/components/Topics/List/TopicTable.tsx
=> Renamed "total partitions" to "partitions"

kafka-ui-react-app/src/components/App.styled.ts, kafka-ui-react-app/src/components/Brokers/Broker/Configs/Configs.styled.ts, kafka-ui-react-app/src/components/Brokers/Broker/Configs/InputCell.tsx, kafka-ui-react-app/src/components/Topics/Topic/MessagesV2/Messages.styled.ts, kafka-ui-react-app/src/components/common/NewTable/Table.styled.ts, kafka-ui-react-app/src/components/common/NewTable/Table.tsx, kafka-ui-react-app/src/theme/theme.ts
- fixes #2650 
- adds scrollable wrapper for table component 
=> Add scrollable wrapper to the new table component

kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/MessageFilters.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/emitter/MessageFiltersTest.java
Record's offsets binding added to smart filter
=> Smart filter offset binding

kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/Filters.tsx, kafka-ui-react-app/src/components/Topics/Topic/Messages/MessagesTable.tsx, kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx
=> Renamed content to value

kafka-ui-react-app/src/components/KsqlDb/Query/Query.tsx, kafka-ui-react-app/src/components/KsqlDb/Query/QueryForm/QueryForm.tsx, kafka-ui-react-app/src/components/KsqlDb/Query/QueryForm/__test__/QueryForm.spec.tsx
=> Fix error with empty fields in Stream properties

kafka-ui-api/pom.xml, pom.xml
Update version of Mockito framework
The workaround mentioned [there](https://github.com/mockito/mockito/issues/2629)
**How Has This Been Tested?** 
**Checklist** 
=> Bump version of mockito up to 4.8.1

pom.xml
=> Update Groovy version up to 3.0.13

.github/workflows/helm.yaml
=> fix helm.yaml

.github/workflows/helm.yaml, charts/kafka-ui/Chart.yaml
=> change app version in charts.yaml

kafka-ui-react-app/src/components/Topics/Topic/Messages/MessageContent/MessageContent.tsx, kafka-ui-react-app/src/components/Topics/Topic/Messages/MessageContent/__tests__/MessageContent.spec.tsx
=> Changed Content to Value and Update a Test

.github/workflows/release-helm.yaml
=> fix release-heml.yaml

kafka-ui-e2e-checks/pom.xml
=> Bump netty version

kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/ConsumerGroupsController.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ConsumerGroupService.java, kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
=> #1362. Drop deprecated method

charts/kafka-ui/Chart.yaml, charts/kafka-ui/templates/deployment.yaml
Adding a checksum for changes to the `configmap_fromValues.yaml` file. This allows the deployment to create new pods when `Values.yamlApplicationConfig` has any changes
Ran `helm template` locally to ensure the annotation is properly updated with an empty map and with test values
**A picture of a cute animal (not mandatory but …
=> adding checksum for config from values

kafka-ui-react-app/src/components/Brokers/utils/__test__/fixtures.ts
i Just made the brokers fixtures mock data sync up with the BE data type , that is being generated by openapi-generator-cli
- [] Unit checks
=> Fix the Brokers' test file fixtures,  mock data to correspond the correct type

kafka-ui-react-app/README.md
I did mange to change react application readme from create-react-app to Vite.
=> ReadMe modification to include Vite.

kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/InfoController.java, kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml, kafka-ui-react-app/src/lib/hooks/api/__tests__/timeFormat.spec.ts, kafka-ui-react-app/src/lib/hooks/api/timeFormat.ts
=> Add a separate endpoint for frontend time format

kafka-ui-react-app/src/components/KsqlDb/Query/renderer/TableRenderer/TableRenderer.styled.tsx
Styling modification to the KSQ DB page
I have added a manual data from the FE side to test the table
=> Full width table display in KSQL_DB page

.github/workflows/release-helm.yaml, charts/kafka-ui/Chart.yaml
=> fix version and workflow

.github/workflows/backend.yml, .github/workflows/branch-deploy.yml, .github/workflows/build-public-image.yml, .github/workflows/cve.yaml, .github/workflows/e2e-checks.yaml, .github/workflows/master.yaml, .github/workflows/release.yaml, documentation/project/contributing/prerequisites.md, kafka-ui-api/Dockerfile, kafka-ui-api/pom.xml, kafka-ui-contract/pom.xml, kafka-ui-e2e-checks/pom.xml, pom.xml
Users of Kafka UI will have to provide a Java 17 (or higher) runtime environment in order to run the application, if not using the Docker image.
Java/OpenJDK 13 has reached end of life (and end of security support) more than 2.5 years ago: https://endoflife.date/java
This change set updates the build, CI pipeline, and Docker image of Kafka UI to Java 17 (LTS). …
=> Feature: Upgrade to Java 17 (Azul Zulu)

kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topic/TopicDetails.java, kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/TopicTests.java
=> fix TopicTest()

.github/workflows/branch-deploy.yml, .github/workflows/build-public-image.yml, .github/workflows/cve.yaml, .github/workflows/delete-public-image.yml, .github/workflows/master.yaml, .github/workflows/release.yaml
> The `set-output` command is deprecated and will be disabled soon.
> Please upgrade to using Environment Files.
> For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> CI: Fix GitHub Actions warnings for `::set-output`

.github/workflows/codeql-analysis.yml, kafka-ui-api/pom.xml
Scan Java source files with CodeQL.
=> CI: Scan Java source files with CodeQL

kafka-ui-react-app/src/lib/hooks/api/topicMessages.tsx
=> Do not cache serdes endpoint results on frontend

kafka-ui-react-app/src/components/common/NewTable/__test__/Table.spec.tsx, kafka-ui-react-app/src/redux/reducers/topicMessages/__test__/selectors.spec.ts
…g in Table.spec.tsx,
fixed non serializable values in selectors.spec.ts
=> Non-serializable warning

kafka-ui-react-app/src/components/Topics/Topic/Statistics/__test__/Statistics.spec.tsx
fixed undefined (reading 'data') warning in Statistics.spec.tsx
=> undefined data warning in Statistics.spec.tsx

pom.xml
=> Fix CVEs, Nov. 2022

.github/workflows/documentation.yaml
=> Excluding serde doc urls from URL check

kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/SerdesInitializer.java
=> Serde autoconfiguration fix

.github/workflows/terraform-deploy.yml
=> [Infra]: Fix terraform deploy

kafka-ui-react-app/src/components/KsqlDb/Query/QueryForm/QueryForm.tsx
=> KSQL: Focus onto query field after incorrect query execution

kafka-ui-serde-api/src/main/java/com/provectus/kafka/ui/serde/api/PropertyResolver.java, kafka-ui-serde-api/src/main/java/com/provectus/kafka/ui/serde/api/Serde.java
=> [Chore] Fix serde api javadoc generation

kafka-ui-react-app/src/components/Topics/Topic/Edit/topicParamsTransformer.ts, kafka-ui-react-app/src/components/Topics/shared/Form/TopicForm.tsx
Topic Edit Page cleanup policy bug fix
=> [FE] Fix cleanup policy submit/display 

.github/workflows/release.yaml
=> fix helm release

charts/kafka-ui/Chart.yaml
=> release 0.4.7

.github/workflows/release-serde-api.yaml
=> fix serde api versioning

charts/kafka-ui/Chart.yaml, charts/kafka-ui/templates/deployment.yaml
=> [Helm] Update spring config location var name

.github/workflows/e2e-checks.yaml
=> Post allure reports to s3 instead of a branch

.github/workflows/e2e-checks.yaml
=> [e2e] [infra] Fix allure reports s3 upload condition

kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/StaticController.java, kafka-ui-react-app/index.html, kafka-ui-react-app/src/components/Cluster/Cluster.tsx, kafka-ui-react-app/src/components/Cluster/__tests__/Cluster.spec.tsx, kafka-ui-react-app/tsconfig.node.json, kafka-ui-react-app/vite.config.ts
i have implemented the on the fly path modification , and enabled the `Lazy loading`
=> [FE] Implement a full support for custom context path

kafka-ui-react-app/index.html, kafka-ui-react-app/package.json, kafka-ui-react-app/pnpm-lock.yaml, kafka-ui-react-app/vite.config.ts
Fix the Development mode public path bug, and making sure the Context servlet path works as well.
=> [FE] Build fails after #2372

kafka-ui-react-app/package.json, kafka-ui-react-app/pnpm-lock.yaml
Remove not used lib from the bundle.
=> remove classnames lib from the bundle

.github/workflows/e2e-checks.yaml
=> [e2e] Fix allure url

kafka-ui-react-app/src/components/Wizard/WizardForm/Authentication/Authentication.tsx, kafka-ui-react-app/src/components/Wizard/WizardForm/KafkaCluster/KafkaCluster.tsx, kafka-ui-react-app/src/components/Wizard/WizardForm/WizardForm.styled.ts, kafka-ui-react-app/src/components/Wizard/WizardForm/WizardForm.tsx, kafka-ui-react-app/src/components/Wizard/schema.ts
=> Wizard kafka cluster form

kafka-ui-react-app/src/components/NavBar/UserInfo/UserInfo.tsx, kafka-ui-react-app/src/components/NavBar/UserInfo/__tests__/UserInfo.spec.tsx
adding basePath logic to the logout functionality
=> Fix URL for Logout button

kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/ConfigTest.java
=> ConfigTest stats initializing added

charts/kafka-ui/Chart.yaml, charts/kafka-ui/templates/ingress.yaml, charts/kafka-ui/values.yaml
=> Add variable for pathtype

README.md, kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/ClustersProperties.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/KafkaCluster.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaClusterFactory.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ReactiveAdminClient.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/StatisticsService.java
=> [BE] Suppressing failures when describe log dirs not supported

kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/TopicsController.java
=> [BE] Fix case-sensitive search in broker's topics (Closes #3043)

kafka-ui-react-app/package.json, kafka-ui-react-app/pnpm-lock.yaml, kafka-ui-react-app/src/components/Topics/Topic/Messages/Message.tsx, kafka-ui-react-app/src/components/Topics/Topic/Messages/MessagesTable.tsx, kafka-ui-react-app/src/components/Topics/Topic/Messages/PreviewModal.styled.ts
Replaced the loadash Get with a JSONPATH library to parse the syntax correctly , fixed the warning tabled embedded in the header.
=> Fix json paths in previews

kafka-ui-react-app/src/components/Wizard/WizardForm/KafkaCluster/KafkaCluster.tsx, kafka-ui-react-app/src/components/Wizard/WizardForm/WizardForm.tsx, kafka-ui-react-app/src/components/Wizard/schema.ts
=> wizard kafka cluster validate

kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/ApplicationConfigController.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClustersStorage.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ReactiveAdminClient.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ksql/KsqlApiClient.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ksql/response/ResponseParser.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/DynamicConfigOperations.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/KafkaClusterValidator.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/ReactiveFailover.java, kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
=> App configuration validation endpoint

.github/workflows/e2e-checks.yaml, kafka-ui-e2e-checks/README.md, kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/settings/configs/Profiles.java, kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/testSuite/TestClass.java, kafka-ui-e2e-checks/src/test/resources/sanity.xml
=> Fix e2e run

kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaClusterFactory.java
=> [BE] SR: maxInMemorySize property setting added to SR client

kafka-ui-api/Dockerfile
=> Using JRE instead of JDK in docker image construction

kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/ApplicationConfigController.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/ClusterMapper.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/ClusterFeature.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalClusterState.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/Statistics.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/FeatureService.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/StatisticsService.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/TopicsService.java, kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Application info API added cluster features enum renamed to `ClusterFeature`
=> Wizard: Application info API

charts/kafka-ui/Chart.yaml
=> [Helm] Release 0.6.0

kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
`croups` -> `groups`
Fixed a typo.
No.
=> Fix typo (groups)

kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/ClustersProperties.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalTopic.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/TopicsService.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/TopicsServicePaginationTest.java, kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topics/TopicsList.java, kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/smokeSuite/topics/TopicsTest.java
=> Implement an internal topic name prefix

.github/workflows/aws_publisher.yaml, .github/workflows/branch-deploy.yml, .github/workflows/build-public-image.yml, .github/workflows/delete-public-image.yml, .github/workflows/e2e-automation.yml, .github/workflows/e2e-checks.yaml, .github/workflows/e2e-weekly.yml, .github/workflows/separate_env_public_create.yml, .github/workflows/terraform-deploy.yml
=> Upgrade aws creds action

kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/CorsGlobalConfiguration.java
=> CORS configuration added

kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/FeatureService.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/StatisticsService.java
Enabling topic deletion by default when controller node not known (fo…r MSG serverless)
=> Topic deletion enabled for MSK Serverless

charts/kafka-ui/Chart.yaml
=> Bump helm version

kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/rbac/extractor/GithubAuthorityExtractor.java, kafka-ui-api/src/main/resources/application-local.yml
=> Fix UserInfoUri usage for Github Enterprise

configuration/authentication/oauth2.md
Documentation update.
Related to #3545.
🦄
=> Update GitHub OAuth configuration for GitHub Enterprise Server

kafka-ui-react-app/src/components/ErrorPage/ErrorPage.styled.ts, kafka-ui-react-app/src/components/ErrorPage/ErrorPage.tsx
renamed Number styled with Status
=> ErrorPage Number variable

kafka-ui-react-app/src/components/common/Editor/Editor.tsx, kafka-ui-react-app/src/components/common/EditorViewer/EditorViewer.styled.ts
I fixed the formatting of styles for proper display when selecting text with the cursor in the data fields passed by the topic
=> Fix Edit config: Selected text background color is transparent

kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ksql/KsqlApiClient.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ksql/KsqlServiceV2.java
1. Fixing ksql response column retrieval (existence check)
2. checking "format" for streams commands if "valueFormat" not set
=> Support for old ksql versions

kafka-ui-react-app/src/components/Topics/Topic/ConsumerGroups/TopicConsumerGroups.styled.ts, kafka-ui-react-app/src/components/Topics/Topic/ConsumerGroups/TopicConsumerGroups.tsx
=> Add consumer search in Topic View #2538

kafka-ui-react-app/src/lib/hooks/api/topics.ts
Rid of "Topic analysis successfully started" message
=> Get rid of "Topic analysis successfully started" message

kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/Permission.java
=> Exempt appconfig from rbac check

kafka-ui-react-app/src/components/Topics/shared/Form/CustomParams/CustomParamField.tsx
=> FE: Fix config param source nullability

kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/BasePage.java, kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/ksqldb/KsqlDbList.java, kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/ksqldb/KsqlQueryForm.java, kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topics/TopicDetails.java, kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/utilities/WebUtils.java, kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/manualsuite/backlog/SmokeBacklog.java, kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/smokesuite/ksqldb/KsqlDbTest.java, kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/smokesuite/topics/MessagesTest.java, kafka-ui-e2e-checks/src/test/resources/regression.xml, kafka-ui-e2e-checks/src/test/resources/sanity.xml, kafka-ui-e2e-checks/src/test/resources/smoke.xml
=> [e2e] Clear entered queue check

charts/kafka-ui/Chart.yaml
=> Bump helm version to 0.6.2

documentation/compose/kafka-ui-serdes.yaml, documentation/compose/proto/values.proto, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/AnyFieldSchema.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/ArrayFieldSchema.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/EnumJsonType.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/FieldSchema.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/JsonType.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/MapFieldSchema.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/ObjectFieldSchema.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/OneOfFieldSchema.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/ProtobufSchemaConverter.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/RefFieldSchema.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/SimpleFieldSchema.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/SimpleJsonType.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/util/jsonschema/ProtobufSchemaConverterTest.java
1. Setting object type for "map" proto fields 
2. `com.provectus.kafka.ui.util.jsonschema. *` classes visibility refactoring
=> BE: Fix protobuf map support

kafka-ui-react-app/src/components/Topics/Topic/Messages/Message.tsx, kafka-ui-react-app/src/components/Topics/Topic/Messages/MessageContent/MessageContent.tsx
Get the sizes from the backend rather than counting text size (bruh). Closes #3688 
=> FE: Fix topic messages Invalid size for null key/value messages

kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/ClustersProperties.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/MessagesController.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/MessagesService.java, kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Making maxPageSize & defaultPageSize configurable
=> BE: Make paging sizes configurable

kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/AddEditFilterContainer.tsx
submitCallback type changed in AddEditFilterContainer.tsx
=> TSC error submit callback type

kafka-ui-api/pom.xml, pom.xml
CVE fixes:  spring-core(6.0.7), transitive org.json
=> CVE fixes:  spring-core(6.0.7), transitive org.json

kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/ConsumerRecordDeserializer.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/SerdesInitializer.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaConnectService.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/analyze/TopicAnalysisStats.java
1. Not setting default key serde to SR/Proto if it is not explicitly set.
2. enabling searching connector by connect name
3. switch using serializedKeySize/serializedValueSize methods instead using byte array len check
=> Minor BE fixes and improvements

kafka-ui-react-app/src/components/Topics/Topic/Messages/Message.tsx, kafka-ui-react-app/src/components/Topics/Topic/Messages/MessageContent/MessageContent.tsx, kafka-ui-react-app/src/components/Topics/Topic/Messages/MessageContent/__tests__/MessageContent.spec.tsx
Fixed display message key/value serdes. Resolves #3117
=> FE: Display message key/value serdes

configuration/helm-charts/quick-start.md
Change to most common way to install helm chart. This helps avoid `git clone` the repo first. 😃
The official helm chart is at https://artifacthub.io/packages/helm/kafka-ui/kafka-ui
But the document didn't mention at all. I found it at https://github.com/provectus/kafka-ui/issues/334#issuecomment-812007248
**A picture of a cute …
=> docs: update helm install way

kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/ApplicationConfigController.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/DynamicConfigOperations.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/AbstractIntegrationTest.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/controller/ApplicationConfigControllerTest.java, kafka-ui-api/src/test/resources/fileForUploadTest.txt, kafka-ui-contract/pom.xml, kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
=> BE: Wizard: Fix file upload

kafka-ui-react-app/src/components/Topics/Topic/Messages/Message.tsx
added Tooltip on Fallback serde icon
=> Implementation Serde fallback icon: Add a tooltip #3716

kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx
changed editors textarea sizes
=> Implementation Messages: Produce pane is too long #3738

kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/ksqldb/KsqlQueryForm.java, kafka-ui-react-app/src/components/Brokers/Broker/Configs/Configs.tsx
Issue Broker's configs search by key is case-sensitive is fixed. Changed to identify case-in-sensitive.
To fix this issue, I have added the toLocaleLowerCase() call in filter method of the tsx file src/components/Brokers/Broker/Configs/Configs.tsx
I'm good here. It is my good first issue. This is not giving any breaking change to the application. 
-After the changes, I did build, run and tested the application. 
Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code …
=> fixed:#3346

kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/KafkaConnectController.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/permission/ConnectAction.java
=> BE: RBAC: Implement restart permission for KC

kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/AccessController.java, kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
=> BE: RBAC: Add missing RBAC action, fix possible exceptions on unknown actions

.github/workflows/e2e-checks.yaml
=> Infra: E2E: Add k-ui healthcheck

kafka-ui-api/src/main/resources/application.yml, kafka-ui-api/src/main/resources/logback-spring.xml
=> logback-spring.xml format upd (removing deprecated `layout`)

kafka-ui-api/pom.xml, pom.xml
- Spring boot upd to 3.0.5
- explicit spring-core version removed
- commons-lang3 upd
- aws-msk-iam-auth upd
Closes #3812
=> BE: Chore: CVEs fixes, May 2023

.github/workflows/aws_publisher.yaml, .github/workflows/branch-deploy.yml, .github/workflows/branch-remove.yml, .github/workflows/master.yaml, .github/workflows/separate_env_public_create.yml, .github/workflows/separate_env_public_remove.yml
=> Infra: Update infra repo remote

kafka-ui-react-app/src/components/Version/Version.tsx
changed warning message on version warning icon
=> FE: Fix latest version is null

kafka-ui-react-app/src/components/Version/Version.tsx
checking if version equals versionTag and show it
=> FE: Fix version display with a tag

kafka-ui-react-app/src/components/Dashboard/ClusterTableActionsCell.tsx, kafka-ui-react-app/src/components/Dashboard/Dashboard.tsx
FE: Fix permissions check for cluster edit. Closes #3835
=> FE: Fix permissions check for cluster edit

kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/KafkaConnectController.java, kafka-ui-react-app/src/components/Connect/Details/Actions/Actions.tsx, kafka-ui-react-app/src/components/Connect/Details/Tasks/ActionsCellTasks.tsx, kafka-ui-react-app/src/components/Connect/List/ActionsCell.tsx, kafka-ui-react-app/src/components/Connect/New/New.tsx
=> RBAC: Fix KC restart permissions

.github/workflows/release.yaml
=> Infra: Fix image build for non OCI-compliant envs

pom.xml
Updated `openapi-generator-maven-plugin.version from 6.5.0` to latest version i.e. 6.6.0
Closes #3034 
=> Update openapi dependency (#3034)

kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaConfigSanitizer.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaConnectService.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/KafkaConfigSanitizerTest.java
=> ISSUE-3916: not failing on null-valued connector's configs values

kafka-ui-react-app/src/widgets/ClusterConfigForm/utils/getJaasConfig.ts, kafka-ui-react-app/src/widgets/ClusterConfigForm/utils/transformFormDataToPayload.ts
=> FE: Wizard: Fix keytab param and boolean params quoting

.github/workflows/branch-deploy.yml, .github/workflows/branch-remove.yml, .github/workflows/build-public-image.yml
=> Infra: post links as checks, not comments

.github/workflows/release.yaml
=> Infra: Release workflow: Call charts action in another repo

kafka-ui-react-app/src/components/ConsumerGroups/Details/Details.tsx, kafka-ui-react-app/src/components/ConsumerGroups/Details/ResetOffsets/ResetOffsets.tsx
=> FE: Disable resetting offsets for unassigned CGs

kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/TopicsController.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/rbac/AccessControlService.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/util/AccessControlServiceMock.java
=> BE: RBAC: Fix viewable topics filter

kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/Filters.tsx
**Issue:**
Issue 3110 -> https://github.com/provectus/kafka-ui/issues/3110
Fixed above issue, where in Topics -> (Topic Name) -> Messages -> Clicking "Clear All" button was not clearing out Timestamp value. 
**Code Changes**
Added `setTimestamp(null);` in `handleClearAllFilters` function inside component `src/components/Topics/Messages/Filter.tsx`
No thing special, since it's a minor UI bug.
Ran the kafka-ui on my local after setting up the local kafka clusters. Go to -> Cluster -> Topic -> Messages -> Choose timestamp and search -> switch to seek type offset -> click clear all -> switch to seek type …
=> 3110: Fixed Timestamp issue on clearall function click

.github/workflows/build-public-image.yml, .github/workflows/delete-public-image.yml
=> Infra: Revert comment action for published images

kafka-ui-react-app/src/components/Brokers/Broker/Broker.tsx, kafka-ui-react-app/src/components/Brokers/Broker/__test__/Broker.spec.tsx, kafka-ui-react-app/src/components/Brokers/BrokersList/BrokersList.tsx, kafka-ui-react-app/src/components/common/NewTable/SizeCell.tsx
=> FE: Add precision for disk usage

kafka-ui-react-app/src/lib/hooks/api/topics.ts
=> FE: Ignore expected 404 on topic statistics page

kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/integration/odd/OddExporter.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/integration/odd/TopicsExporter.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/integration/odd/TopicsExporterTest.java, kafka-ui-react-app/src/lib/hooks/api/topics.ts
=> ODD: Skipping topic exporting if we failed to load/parse topic's schema from SR

.github/workflows/master.yaml
=> Infra: Fix image build for non OCI-compliant runtimes

kafka-ui-react-app/src/components/ConsumerGroups/List.tsx
=> FE: Consumers: Replace zero consumer lag with "N/A"

.github/workflows/backend.yml, .github/workflows/e2e-checks.yaml, .github/workflows/frontend.yaml, .github/workflows/pr-checks.yaml, .github/workflows/welcome-first-time-contributors.yml
=> Infra: tighten github_token security

kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/SchemaRegistryService.java
Error message from SR propagation added
=> Error message from SR propagation

kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/AvroEmbeddedSerde.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/Base64Serde.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/Int64Serde.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/UInt64Serde.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/UuidBinarySerde.java
=> BE: Serde tiny improvements and fixes 

kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/KafkaConnectMapper.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaConnectService.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/integration/odd/ConnectorsExporter.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/AbstractIntegrationTest.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/integration/odd/ConnectorsExporterTest.java
1. suppressing connect errors when returning list of all connectors
2. minor refactoring of KafkaConnectService.getAllConnectors
=> BE: KC: Suppress unavailable connects

kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/Permission.java
=> BE: RBAC: Fix unknown resource exception

kafka-ui-api/Dockerfile
While viewing container logs the default timezone is UTC, and re-configuring such would require a tzdata package installed. It's inconvenient to rebuild the image just for that cause.
=> Make the container timezone configurable

kafka-ui-react-app/src/components/Topics/List/ActionsCell.tsx, kafka-ui-react-app/src/components/Topics/Topic/Topic.tsx
=> FE: Update topic deletion disabled message

.github/workflows/frontend.yaml
=> Infra: Fix frontend sonar jdk warning

kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/audit/AuditService.java
RBAC might be disabled thus audit won't be able to cast user details. 
Make it possible to fetch details for both RBAC and non-RBAC users.
Fixes #4131
=> BE: Audit: consider RBAC might be disabled

kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/ApplicationConfigController.java
Minor restart logic refactoring
=> BE: Minor restart logic refactoring

kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/CorsGlobalConfiguration.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/WebclientProperties.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/AuthenticatedUser.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/RbacOAuth2User.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/RbacOidcUser.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/AccessController.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/BrokersController.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/ConsumerGroupsController.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/KafkaConnectController.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/SchemasController.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/TopicsController.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/OffsetsInfo.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/exception/GlobalErrorWebExceptionHandler.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/ClusterMapper.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/DescribeLogDirsMapper.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalLogDirStats.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/AccessContext.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/Base64Serde.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/ConsumerOffsetsSerde.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/Int32Serde.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/sr/SchemaRegistrySerde.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/metrics/WellKnownMetrics.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/rbac/AccessControlService.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/JsonAvroConversion.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/ProtobufSchemaConverter.java, kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/models/Schema.java, kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/pages/topics/TopicCreateEditForm.java
- Remove unused imports
- Remove deprecated code
Resolves #1911
=> Fix sonar code issues

README.md
I fixed the persistent start install link in the README because the current link is broken.
=> Fix persistent installation link in README

pom.xml
This should get the latest versions of:
org.springframework.security:spring-security-config
org.springframework.security:spring-security-core
org.springframework.boot:spring-boot-autoconfigure
Which should fix the following CVEs
CVE-2023-34034
CVE-2023-20883
Ensuring the deps are upgraded. I don't use maven regularly.
**A picture of …
=> Bump Spring Boot version to 3.1.3
