provectus/kafka-ui

kafka-ui-api/src/main/java/com/provectus/kafka/ui/rest/config/CustomWebFilter.java, kafka-ui-react-app/src/components/App.tsx, kafka-ui-react-app/src/components/ConsumerGroups/ConsumerGroups.tsx, kafka-ui-react-app/src/components/Nav/Nav.tsx, kafka-ui-react-app/src/components/Topics/Topics.tsx, kafka-ui-react-app/src/lib/paths.ts
#31 
this is a workaround for the issue spotted by @germanosin https://provectus.slack.com/archives/CUGP7S38R/p1586432424004700
on reload backend tries to render any route on its own instead of using react routing
it was agreed to add /ui/ prefix for ui routes
=> issue-31/add-ui-prefix-for-react-routes

kafka-ui-react-app/src/components/Topics/New/New.tsx, kafka-ui-react-app/src/redux/api/topics.ts
Topic is not creatable with no custom params (spread merging undefined)
pay attention to https://github.com/provectus/kafka-ui/pull/37/files#diff-49f415954bd30f9765f7c00b7d0cd903R53 - the one and only thing changed
=> fix-bug-topic-not-creatable-when-no-custom-params

kafka-ui-react-app/src/components/Topics/Details/Details.tsx
needed to add /ui/ for these routes as well
=> fix-routes-for-details

kafka-ui-react-app/package.json
This is needed because otherwise UI trying to construct full URI during build process, and we cannot use the same docker image for production and local deployments, if we just mentioned relative path, the same image can work for any deployments/domain names.
=> endpoint was changed to get rid from domain name path

.gitignore, chart/kafka-ui/.helmignore, chart/kafka-ui/Chart.yaml, chart/kafka-ui/README.md, chart/kafka-ui/templates/NOTES.txt, chart/kafka-ui/templates/_helpers.tpl, chart/kafka-ui/templates/configmap.yaml, chart/kafka-ui/templates/deployment.yaml, chart/kafka-ui/templates/hpa.yaml, chart/kafka-ui/templates/ingress.yaml, chart/kafka-ui/templates/secret.yaml, chart/kafka-ui/templates/service.yaml, chart/kafka-ui/templates/serviceaccount.yaml, chart/kafka-ui/values.yaml
A simple Helm Chart with configuring application via environments variables, we able to pass environments from an existing secret/configmap or/and generate secret/configmap based on the Helm release values. Also, the sample deployment with Apache Kafka has been added as an example.
=> Helm Chart added

kafka-ui-api/src/main/java/com/provectus/kafka/ui/cluster/exception/GlobalErrorWebExceptionHandler.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/cluster/service/SchemaRegistryService.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/rest/MetricsRestController.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/SchemaRegistryServiceTests.java, kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
**Changes**
* Updated interfaces to use **Schema Registry** terminology: _schemaName_ -> _subject_
* Refactored `getSchemas` method to return an array of latest schemas instead of just an array of subject names
* Fixed getting an error code from attributes in our custom `GlobalErrorWebExceptionHandler`
* Updated tests
=> Issue-181 Refactor schema CRUD API

README.md
The command will fail with `zsh: command not found: -e` without line-continuation
=> MINOR: Add line-continuation to shell command

kafka-ui-api/src/main/java/com/provectus/kafka/ui/cluster/config/ClustersProperties.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/cluster/exception/ReadOnlyException.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/cluster/model/KafkaCluster.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/rest/config/ReadOnlyModeFilter.java, kafka-ui-api/src/main/resources/application-local.yml, kafka-ui-api/src/test/java/com/provectus/kafka/ui/AbstractBaseTest.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/KafkaConnectServiceTests.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/ReadOnlyModeTests.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/SchemaRegistryServiceTests.java, kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Added `WebFilter` for filtering out all `POST` requests if cluster is configured to be read-only
=> #164 readonly mode

kafka-ui-api/src/test/java/com/provectus/kafka/ui/AbstractBaseTest.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/KafkaConnectContainer.java
Moved testcontainers lifecycle control back to singleton.
Right now we are creating new container for every test and it's too much IMO, with singleton containers we both reduce overall build/test time and reduce possible error counts during the build, considering every container start is error prone.
Сhanged kafka connect container wait strategy from log pattern to http request - waiting for log times out from time to time.
=> Testcontainers speedup and stabilization

kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/ClusterMapper.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/Feature.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/KafkaCluster.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClustersStorage.java, kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Example response:
```
[
{
"brokerCount": 1,
"bytesInPerSec": 0,
"bytesOutPerSec": 0,
"defaultCluster": null,
"features": [],
"name": "secondLocal",
"onlinePartitionCount": 57,
"readOnly": false,
"status": "online",
"topicCount": 5
},
{
"brokerCount": 2,
"bytesInPerSec": 0,
"bytesOutPerSec": 0,
"defaultCluster": null,
"features": [
"KAFKA_CONNECT",
"SCHEMA_REGISTRY"
],
"name": "local",
"onlinePartitionCount": 85,
"readOnly": false,
"status": "online",
"topicCount": 7
}
]
```
=> added features field to kafka cluster

kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml, kafka-ui-react-app/src/components/common/BytesFormatted/BytesFormatted.tsx, kafka-ui-react-app/src/components/common/BytesFormatted/__tests__/BytesFormatted.spec.tsx
Now UI will not display the number if it is negative but will show `-Bytes` instead.
=> #289: Negative segment size

charts/kafka-ui/templates/service.yaml, charts/kafka-ui/values.yaml
to deploy kafka-ui with nodePort add those commands when you install/update the chart
--set service.type=NodePort --set service.nodePort=31000
=> add nodePort support

kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/ConsumerGroupsController.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClusterService.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaService.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/ClusterUtil.java, kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Added topic level consumer groups members:
```
/api/clusters/{clusterName}/topics/{topicName}/consumergroups
```
And extended consumer groups details with state, simple, assignor
=> #121 Topic level consumer groups & consumer group details

kafka-ui-react-app/src/components/Schemas/Details/Details.tsx, kafka-ui-react-app/src/components/Schemas/Details/DetailsContainer.ts, kafka-ui-react-app/src/components/Schemas/Details/__test__/Details.spec.tsx, kafka-ui-react-app/src/components/Schemas/Details/__test__/__snapshots__/Details.spec.tsx.snap, kafka-ui-react-app/src/redux/actions/__test__/thunks/schemas.spec.ts, kafka-ui-react-app/src/redux/actions/actions.ts, kafka-ui-react-app/src/redux/actions/thunks/schemas.ts, kafka-ui-react-app/src/redux/reducers/schemas/__test__/reducer.spec.ts, kafka-ui-react-app/src/redux/reducers/schemas/reducer.ts, kafka-ui-react-app/src/redux/reducers/topics/__tests__/reducer.spec.ts
Now a certain schema can be deleted from its page
=> Deleting schemas

kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/KafkaConnectController.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/KafkaConnectMapper.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaConnectService.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/KafkaConnectServiceTests.java, kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
=> #356 added endpoint to fetch all cluster connectors

kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/TopicsController.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClusterService.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/ClusterServiceTest.java, kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
=> #187 added search and sorting

kafka-ui-api/pom.xml
Spring starter add additional dependency `spring-security-oauth2-jose`. It is needed if you want to configure generic oauth provider such as AWS cognito.
=> Use spring oauth2 starter as dependency 

kafka-ui-api/src/main/resources/application.yml
When this default cluster configuration is setup, user have to override complete first cluster. Eg have to set KAFKA_CLUSTERS_0_ZOOKEEPER to empty string to override default localhost.
=> Remove default cluster configuration.

kafka-ui-react-app/src/components/Topics/List/ListItem.tsx, kafka-ui-react-app/src/components/Topics/List/__tests__/ListItem.spec.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/Details.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/DetailsContainer.ts, kafka-ui-react-app/src/components/Topics/Topic/Details/Overview/Overview.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/Overview/__test__/Overview.spec.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/__test__/Details.spec.tsx, kafka-ui-react-app/src/redux/reducers/topics/selectors.ts
User should not be able to update/delete internal topics. Add confirmation for all delete/reset actions
if topic is internal you don't see an action button
=> [issues-357] - User should not be able to update/delete

kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessageItem.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessagesTable.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/__test__/MessageItem.spec.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/__test__/__snapshots__/MessageItem.spec.tsx.snap, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/__test__/__snapshots__/MessagesTable.spec.tsx.snap, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/__test__/fixtures.ts
add column key, and render value
=> The key of the message is not visible / accessible #377

kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/KafkaConnectMapper.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/connect/InternalConnectInfo.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaConnectService.java, kafka-ui-contract/src/main/resources/swagger/kafka-connect-api.yaml
Now we can get a valid list of topics that are used by a connector.
If the connector type is **SOURCE**, then the list is where it sends messages,
If the connector type is **SINK**, where it consumes from.
**After**
The connectors are set up to deal with multiple topics. Some of them use regexs or `topic`, `topics` properties  
=> [Kafka Connect] Fix getting list of connector's topics

kafka-ui-react-app/src/components/Topics/shared/Form/TopicForm.tsx
After updating react-hook-form to the latest version a bug appeared in the component for creating a new topic - the values of the form were `undefined`, after the form fields became disabled. That resulted in redirecting to `topics/undefined` after the topic was successfully created. Official documentation [suggests](https://react-hook-form.com/api/useform/getvalues/) that we should disable the whole `fieldset` in such cases.
**How Has This Been Tested?**
=> Fix redirect to a newly created topic

README.md, docker/kafka-ui-reverse-proxy.yaml, docker/proxy.conf, kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/Config.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/CustomWebFilter.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/StaticController.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/deserialization/ProtobufFileRecordDeserializer.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/deserialization/RecordDeserializer.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/deserialization/SchemaRegistryRecordDeserializer.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/deserialization/SimpleRecordDeserializer.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/NumberUtil.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/ResourceUtil.java, kafka-ui-react-app/.env, kafka-ui-react-app/package-lock.json, kafka-ui-react-app/package.json, kafka-ui-react-app/public/index.html, kafka-ui-react-app/src/index.tsx, kafka-ui-react-app/src/lib/constants.ts
- changed webfilter for spring boot app
- usage of relative paths in index.html file
These changes will resolve #364, to test this deployment case need to execute `docker compose up -f docker/kafka-ui-reverse-proxy.yaml`, it simulates the same behavior as ingress with custom basePath in K8s
=> Add ability to use custom basePath

kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClusterService.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/ClusterServiceTest.java
=> #518 Fixed backend page size

kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
Introduced the new query field for the GET topic message request - seekDirection. It can have two values - _FORWARD_ (forward in time, show messages starting from the oldest ones) and _BACKWARD_ (backward in time, show messages starting from the newest ones). I'm not sure if these literals are the best choice for the values. Maybe something like _NEWEST_FIRST_ and _OLDEST_FIRST_ is more intuitively understandable.
The front-end implementation plan is to have some kind of a toggle, which controls the sorting direction of the list.
=> Add SeekDirection to the GET topic messages request

kafka-ui-react-app/src/components/Connect/List/ListItem.tsx, kafka-ui-react-app/src/components/Connect/List/__tests__/__snapshots__/ListItem.spec.tsx.snap
Turned the table cell for topic names into the flexbox container with the `flex-wrap` property. Also, every link is now styled as a tag, so that different links are now visually separatable.
=> Add wrapping for topic names

charts/kafka-ui/README.md, charts/kafka-ui/templates/NOTES.txt
Fix #556 
Kafka-ui is available on port 8080 of the pod. So `kubectl port-forward` shall be called with 8080 as REMOTE_PORT
=> Fix 556. Kafka-ui is available on port 8080

kafka-ui-react-app/src/components/Topics/Topic/Details/ConsumerGroups/TopicConsumerGroups.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/ConsumerGroups/TopicConsumerGroupsContainer.ts, kafka-ui-react-app/src/components/Topics/Topic/Details/ConsumerGroups/__test__/TopicConsumerGroups.spec.tsx, kafka-ui-react-app/src/redux/interfaces/topic.ts, kafka-ui-react-app/src/redux/reducers/topics/selectors.ts
This part of the application was implemented incorrectly. One thing was fetched from the backend, but absolutely another shown on the page. Fixed the inconsistency.
=> Properly display the list of topic consumers

README.md
Adding details of KafkaConnect environments in the readme to be easier to find for users
=> Adding details of KafkaConnect environments in the readme

kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/CustomWebFilter.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/MessagesController.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/BackwardRecordEmitter.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/ForwardRecordEmitter.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/ConsumerPosition.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/schemaregistry/JsonMessageReader.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/schemaregistry/MessageReader.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/schemaregistry/ProtobufMessageReader.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ConsumingService.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaService.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/OffsetsSeek.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/OffsetsSeekBackward.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/OffsetsSeekForward.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/EnumJsonType.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/jsonschema/JsonSchema.java, kafka-ui-api/src/main/resources/application-sdp.yml, kafka-ui-api/src/test/java/com/provectus/kafka/ui/AbstractBaseTest.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/KafaConsumerGroupTests.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/KafkaConsumerGroupTests.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/RecordEmitterTest.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/util/OffsetsSeekTest.java
=> #122 Fix emitter to consume records in right order

charts/kafka-ui/templates/deployment.yaml
#511 introduced custom basePath, however when custom basePath is used than Helm chart livenessProbe and readinessProbe will fail because it will try to probe on the default path`/` which does not exist anymore. With these changes it automatically picks up `SERVER_SERVLET_CONTEXT_PATH` from the myconfig.yaml and sets correct path for livenessProbe and readinessProbe
#511 introduced custom basePath, however when custom basePath is used than Helm chart livenessProbe and readinessProbe will fail because it will try to probe on the default path `/` which does not exist anymore. With these changes it automatically picks up `SERVER_SERVLET_CONTEXT_PATH` from the myconfig.yaml and sets correct path for livenessProbe and readinessProbe
**Is there …
=> fix: Helm chart - livenessProbe and readinessProbe with custom basePath

charts/kafka-ui/templates/ingress.yaml, charts/kafka-ui/values.yaml
Introducing precedingPaths in the Ingress object. With the help of the precedingPaths you can to SSL redirect on the ingress controller side. Inspired by Airflow Helm chart web ingress object.
BREAKING CHANGE: Ingress object changed.
- Helm chart ingress object configuration changed
Introducing precedingPaths in the Ingress object. With the help of the precedingPaths you can to SSL redirect on the ingress controller side. Inspired by Airflow Helm chart web ingress object.
Deployin helm chart to an EKS cluster
Check out …
=> feat: Helm chart ingress refactor and SSL redirect

kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/ConsumerGroupsController.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaService.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/OffsetsResetService.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/OffsetsResetServiceTest.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/util/jsonschema/AvroJsonSchemaConverterTest.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/util/jsonschema/ProtobufSchemaConverterTest.java, kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml, pom.xml
This PR contains backend implementation for offsets reset functionality. Supported reset types are: 
- earliest
- latest
- to specific offset
- to timestamp. 
As an inspiration I used https://cwiki.apache.org/confluence/display/KAFKA/KIP-122%3A+Add+Reset+Consumer+Group+Offsets+tooling doc. 
=> #234: Consumer group offsets reset implementation

kafka-ui-react-app/package-lock.json, kafka-ui-react-app/package.json, kafka-ui-react-app/src/components/Topics/List/List.tsx, kafka-ui-react-app/src/components/Topics/List/ListContainer.ts, kafka-ui-react-app/src/components/Topics/List/__tests__/List.spec.tsx, kafka-ui-react-app/src/components/Topics/List/__tests__/__snapshots__/List.spec.tsx.snap, kafka-ui-react-app/src/redux/actions/thunks/topics.ts, kafka-ui-react-app/src/redux/reducers/topics/selectors.ts
- refetch topics on `showInternal` change
- added and refactored tests for TopicsList component 
=> [#710] feat(react-app): call fetchTopics on toggle show internal topics

kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx
After manually testing the message sending form, I noticed a bug that happens when either key or value of the message schema has a type other than `object`, for example, `string`: 
```json
{
"key":{
"name":"unknown",
"source":"SOURCE_SCHEMA_REGISTRY",
"schema":"{\"$id\":\"http://unknown.unknown\",\"$schema\":\"https://json-schema.org/draft/2020-12/schema\",\"type\":\"string\"}"
},
}
```
Turns out that the json-schema-to-yup-transformer can handle only `objects` as the base type. The same applies to other json schema to yup converters. Some return `undefined`, others throw an error. I added a small fix, so that the message sending form doesn't become an infinite page loader when both key and message are not object, but it is a temporal fix because no validation happens in this case. 
Right …
=> Fix sending messages form

README.md, docker/kafka-ui-zookeeper-ssl.yml, kafka-ui-api/pom.xml, kafka-ui-api/src/main/java/com/provectus/kafka/ui/exception/ZooKeeperException.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaService.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ZookeeperService.java, pom.xml
Replaced the zookeeper client for a few reasons:
1) The previous client we've used does not support TLS as it seems
2) The author/maintainer or the client we've used has been inactive on github since 2018-ish with all the emerging issues.
As a result I had to add the maven central repo to fetch the official apache zookeeper client dependency since it's not being present in confluent repo.
I've provided an example docker-compose file which supports TLS enabled zookeeper. Tell me if I need to commit the truststore/keystore files as well.
Check out …
=> TLS enabled zookeeper

kafka-ui-react-app/package-lock.json, kafka-ui-react-app/package.json
Reverts provectus/kafka-ui#760
=> Revert "Bump react-hook-form from 7.6.9 to 7.12.2 in /kafka-ui-react-app"

kafka-ui-api/src/main/java/com/provectus/kafka/ui/strategy/ksql/statement/ShowStrategy.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/KsqlServiceTest.java
- fixed issue with parallel ksql requests for ShowStrategy. ShowStrategy has property `responseValueKey` which required for response mapping. Parallel requests were rewriting this property. Fix returns new instance of ShowStrategy.
=> KSQL: fixed ShowStatement behaviour for parallel requests

kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx, kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessageContainer.ts, kafka-ui-react-app/src/components/Topics/Topic/SendMessage/__test__/SendMessage.spec.tsx, kafka-ui-react-app/src/redux/reducers/topics/selectors.ts
Since I used the redux loader to detect if the message was sent and we can redirect to another page, it led to a bug when we cannot go to the message sending page after the message was already sent - it was simply redirected immediately. I removed this part of redux entirely and redirect right after the form was submitted. This is not a perfect solution, since we do not wait for the backend response and it can lead to a race condition of some kind, but I see no other solution for now. 
I believe, we need some mechanism for manual resetting of redux loaders.
=> Redirect right after a message is sent

kafka-ui-react-app/src/redux/reducers/topicMessages/reducer.ts
After sending a request for clearing the topic messages, nothing happened locally, a user had to reload the page to see the results. Now the messages are cleared from the store after a successful request
=> Clear topic messages locally

kafka-ui-react-app/src/components/Topics/Topic/Details/Details.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/DetailsContainer.ts, kafka-ui-react-app/src/components/Topics/Topic/Details/__test__/Details.spec.tsx, kafka-ui-react-app/src/redux/actions/actions.ts, kafka-ui-react-app/src/redux/reducers/loader/reducer.ts, kafka-ui-react-app/src/redux/reducers/topics/selectors.ts
Turns out that the previous solution was faulty. It required the list of topics to be in the store in order to search through it. But when we accessed the topic details page from a direct link, it was not fetched. 
Fetching this list inside the details component didn't help, cause the hook that is responsible for the redirect after deletion was running before the response from the topics list fetching was coming. And keeping track of the number of component re-renders felt like a костыль and is kinda ugly.
So added a way to manually reset the value of the loader state.
=> Fix redirect after the topic deletion

kafka-ui-react-app/src/components/ConsumerGroups/Details/Details.tsx, kafka-ui-react-app/src/components/Topics/List/List.tsx, kafka-ui-react-app/src/components/Topics/List/ListItem.tsx
Fixed an issue with read-only cluster flag not affecting topic multi-select checkboxes and consumers' `reset offsets` and `delete consumer group`
=> Fix readonly cluster error

kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/ClustersProperties.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/KafkaCluster.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/DeserializationService.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/ProtobufFileRecordSerDe.java, kafka-ui-api/src/main/resources/application-local.yml, kafka-ui-api/src/test/java/com/provectus/kafka/ui/serde/ProtobufFileRecordSerDeTest.java, kafka-ui-api/src/test/resources/address-book.proto
**What changes did you make?** Added the ability to specify separate message types for each topic when using ProtobufFile for deserialization. The configuration `protobufMessageName` is now a map between the topic name and the message name. The key `_default` is used for specifying the message name for all other topics not defined explicitly.
=> ISSUE-849: Use a map between topics and message-names when using ProtobufFile

kafka-ui-react-app/src/redux/reducers/consumerGroups/selectors.ts
For some reason, there was a wrong action name in the fetching selector.
=> Fix redirect after resetting consumer group offsets

kafka-ui-react-app/package-lock.json, kafka-ui-react-app/package.json, kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx, kafka-ui-react-app/src/components/Topics/Topic/SendMessage/__test__/SendMessage.spec.tsx, kafka-ui-react-app/src/components/Topics/Topic/SendMessage/__test__/fixtures.ts, kafka-ui-react-app/src/components/Topics/Topic/SendMessage/validateMessage.ts
Previously we converted json-schema to yup, generated fake data, and validated it. This solution was not very good, because the libs we used for that were faulty. We didn't use json-schema-faker because it had bugs, but they fixed them in recent updates. 
Also, I refactored some code here.
=> Rewrite the message generation to json-schema-faker and the message validation to ajv

kafka-ui-react-app/src/components/ConsumerGroups/Details/ListItem.tsx, kafka-ui-react-app/src/components/ConsumerGroups/Details/ResetOffsets/ResetOffsets.tsx, kafka-ui-react-app/src/components/ConsumerGroups/Details/ResetOffsets/ResetOffsetsContainer.ts, kafka-ui-react-app/src/components/ConsumerGroups/Details/ResetOffsets/__test__/ResetOffsets.spec.tsx, kafka-ui-react-app/src/redux/actions/actions.ts
Fixed some stuff:
1. Changed the broken link in the topics list
2. Fixed the issue with loader selector bring set to 'fetched' after resetting consumers group and not allowing to visit the page again.
=> Fix consumer groups page

kafka-ui-react-app/src/components/Topics/List/__tests__/__snapshots__/List.spec.tsx.snap, kafka-ui-react-app/src/components/Topics/New/New.tsx, kafka-ui-react-app/src/components/Topics/New/__tests__/New.spec.tsx, kafka-ui-react-app/src/components/Topics/Topic/Edit/Edit.tsx, kafka-ui-react-app/src/components/Topics/shared/Form/TopicForm.tsx, kafka-ui-react-app/src/components/common/Button/Button.styled.ts, kafka-ui-react-app/src/components/common/Button/Button.tsx, kafka-ui-react-app/src/components/common/Input/Input.styled.ts, kafka-ui-react-app/src/components/common/Input/Input.tsx, kafka-ui-react-app/src/components/common/Input/InputIcon.styled.ts, kafka-ui-react-app/src/components/common/Input/__tests__/Input.spec.tsx, kafka-ui-react-app/src/components/common/Input/__tests__/__snapshots__/Input.spec.tsx.snap, kafka-ui-react-app/src/components/common/Search/Search.tsx, kafka-ui-react-app/src/components/common/Search/__tests__/Search.spec.tsx, kafka-ui-react-app/src/components/common/Search/__tests__/__snapshots__/Search.spec.tsx.snap, kafka-ui-react-app/src/lib/yupExtended.ts
Created custom inputs. They can either be a part of the react-hook-form or stand-alone inputs. The API is the following:
1. One shouldn't register the Input component in the react-hook-form directly, but rather pass the name and config like that:
```jsx
<Input
name="name"
hookFormOptions={{
required: 'Topic Name is required.',
pattern: {
value: TOPIC_NAME_VALIDATION_PATTERN,
message: 'Only alphanumeric, _, -, and . allowed',
},
}}
placeholder="Topic Name"
defaultValue={topicName}
/>
```
If we were to register it directly, some of the functionality would break.
2. In order to add icons to the input, one should pass the FA class to the respective prop like this:
```jsx
<Input
className="input"
type="number"
defaultValue="1000012"
name="maxMessageBytes"
hookFormOptions={{
required: 'Maximum …
```
=> Custom Inputs 

kafka-ui-react-app/src/components/Topics/New/__tests__/New.spec.tsx, kafka-ui-react-app/src/components/Topics/shared/Form/TopicForm.tsx, kafka-ui-react-app/src/components/__tests__/__snapshots__/App.spec.tsx.snap, kafka-ui-react-app/src/components/common/Select/LiveIcon.styled.tsx, kafka-ui-react-app/src/components/common/Select/Select.styled.ts, kafka-ui-react-app/src/components/common/Select/Select.tsx, kafka-ui-react-app/src/components/common/Select/__tests__/Select.spec.tsx, kafka-ui-react-app/src/components/common/Select/__tests__/__snapshots__/Select.spec.tsx.snap, kafka-ui-react-app/src/theme/theme.ts
Custom selects. The API is similar to inputs: 
1. Provide `name` to register it in the react-hook-form, although the validation must be done through an external resolver.
2. There are two sizes - M and L
3. Pass the `isLive` prop to add this red dot on the left to indicate that the change of the select will have an immediate effect.
=> Custom select

kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/schemaregistry/AvroMessageFormatter.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/SendAndReadTests.java
KafkaAvroDeserializer returns GenerericRecord only if schema has "record" type, in case of primitive types it will return corresponding java object.
=> Unnecessary casting removed from AvroFormatter to fix primitive values deserialization

kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/Config.java
webclient.max-in-memory-buffer-size property added
=> Property to tune WebClient's max buffer sized added

kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.tsx
URL for the EventSource for the topic messages was not taking the basePath into the consideration. Now it does.
=> Fix topic messages fetch

kafka-ui-react-app/src/components/Brokers/Brokers.tsx, kafka-ui-react-app/src/components/Brokers/__test__/Brokers.spec.tsx, kafka-ui-react-app/src/components/Brokers/__test__/__snapshots__/Brokers.spec.tsx.snap, kafka-ui-react-app/src/components/KsqlDb/List/List.tsx, kafka-ui-react-app/src/components/Topics/shared/Form/TopicForm.tsx, kafka-ui-react-app/src/components/__tests__/__snapshots__/App.spec.tsx.snap, kafka-ui-react-app/src/components/common/Dashboard/Indicator.tsx, kafka-ui-react-app/src/components/common/Dashboard/MetricsWrapper.tsx, kafka-ui-react-app/src/components/common/Dashboard/__tests__/MetricsWrapper.spec.tsx, kafka-ui-react-app/src/components/common/Dashboard/__tests__/__snapshots__/Indicator.spec.tsx.snap, kafka-ui-react-app/src/components/common/Tag/Tag.styled.tsx, kafka-ui-react-app/src/lib/testHelpers.tsx, kafka-ui-react-app/src/theme/theme.ts
I have fully rewritten Metrics. The API almost didn't change: `MetricsWrapper` accepts title as a prop and `Indicator`s as children.`Indicator`s accept their content as children.
Rewritten Brokers page - moved third metrics block to the table, just like in design:
In case of vertical overflow, I added scroll:
=> Fix Metrics

kafka-ui-react-app/src/components/App.scss, kafka-ui-react-app/src/components/Brokers/__test__/__snapshots__/Brokers.spec.tsx.snap, kafka-ui-react-app/src/components/Nav/ClusterMenu.tsx, kafka-ui-react-app/src/components/Nav/ClusterMenuItem/ClusterMenuItem.styled.ts, kafka-ui-react-app/src/components/Nav/ClusterMenuItem/ClusterMenuItem.tsx, kafka-ui-react-app/src/components/Nav/ClusterMenuItem/ClusterTab/ClusterTab.styled.ts, kafka-ui-react-app/src/components/Nav/ClusterMenuItem/ClusterTab/ClusterTab.tsx, kafka-ui-react-app/src/components/Nav/ClusterMenuItem/ClusterTab/ClusterTabChevron.tsx, kafka-ui-react-app/src/components/Nav/ClusterMenuItem/ClusterTab/__tests__/ClusterTab.spec.tsx, kafka-ui-react-app/src/components/Nav/ClusterMenuItem/ClusterTab/__tests__/__snapshots__/ClusterTab.spec.tsx.snap, kafka-ui-react-app/src/components/Nav/ClusterMenuList/ClusterMenuList.styled.ts, kafka-ui-react-app/src/components/Nav/ClusterStatusIcon.tsx, kafka-ui-react-app/src/components/Nav/DefaultClusterIcon.tsx, kafka-ui-react-app/src/components/Nav/Nav.tsx, kafka-ui-react-app/src/components/Nav/__tests__/ClusterMenu.spec.tsx, kafka-ui-react-app/src/components/Nav/__tests__/ClusterMenuItem.spec.tsx, kafka-ui-react-app/src/components/Nav/__tests__/ClusterStatusIcon.spec.tsx, kafka-ui-react-app/src/components/Nav/__tests__/Nav.spec.tsx, kafka-ui-react-app/src/components/Nav/__tests__/__snapshots__/ClusterMenuItem.spec.tsx.snap, kafka-ui-react-app/src/components/Nav/__tests__/__snapshots__/ClusterStatusIcon.spec.tsx.snap, kafka-ui-react-app/src/components/Nav/__tests__/__snapshots__/Nav.spec.tsx.snap, kafka-ui-react-app/src/components/Topics/List/__tests__/__snapshots__/List.spec.tsx.snap, kafka-ui-react-app/src/components/__tests__/__snapshots__/App.spec.tsx.snap, kafka-ui-react-app/src/theme/theme.ts
Finished styling the menu:
The cluster tab (the one with chevron and an online status indicator) is now not a `NavLink`, but rather a button that triggers the `ClusterMenu` to be unfolded:
=> Redesign menu

kafka-ui-api/pom.xml, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaConfigSanitizer.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaConnectService.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/KafkaConnectServiceTests.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/KafkaConfigSanitizerTest.java, kafka-ui-react-app/src/components/Connect/Edit/Edit.tsx, kafka-ui-react-app/src/components/Connect/Edit/__tests__/Edit.spec.tsx, kafka-ui-react-app/src/components/Connect/Edit/__tests__/__snapshots__/Edit.spec.tsx.snap
- BE: add KafkaConfigSanitizer. Sanitize Kafka Connector configs when fetching
- FE: add a banner message to edit connector config page to warn people to not forget about the credentials.
Screenshots for the changes.
Fixes #980 
=> #980: sanitize credentials in Kafka Connector configs. Add a warning to edit page when people try to edit configs with obfuscated field

charts/kafka-ui/templates/deployment.yaml
Fix health/readiness path in order to align current development, 
We decided to make specific health path to check service availability even if kafka-ui configured with authorization. 
/actuator/health return 2XX codes despite of authorization settings
=> Fix health/readiness path

kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/MessagesController.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/MessagesService.java
removed Consumer API usage for offset manupulation
=> ISSUE-874: Using AdminClient for offsets retrieval instead of Consumer

README.md
The value "all" for LOGGING_LEVEL_ROOT is logged as invalid at startup:
java.lang.IllegalArgumentException: No enum constant org.springframework.boot.logging.LogLevel.all
**What changes did you make?**
README update to fix the highest logging value.
The value "all" for LOGGING_LEVEL_ROOT is logged as invalid at startup:
java.lang.IllegalArgumentException: No enum constant org.springframework.boot.logging.LogLevel.all
The value "trace" is valid and increase the verbosity as compared to debug. …
=> The highest logging level is "trace", not "all"

kafka-ui-api/src/main/java/com/provectus/kafka/ui/exception/GlobalErrorWebExceptionHandler.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalClusterState.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ClustersMetricsScheduler.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/MetricsCache.java, kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
1. stacktrace field added to error responses
2. lastError added to Cluster responce
3. blocking metrics initialization on startup changed to async init (returned to prev behavior)
=> Metrics collection init & stacktrace addition to error responses

docker/connectors/github-source.json, docker/connectors/s3-sink.json, docker/kafka-connect/Dockerfile, docker/kafka-ui-connectors.yaml, docker/kafka-ui.yaml
1. Now when running kafka-ui-connectors.yaml connectors for S3 and GitHub are automatically installed within the kafka-connect container.
2. Connectors json config file templates added to docker/connectors directory.
=> Added Connector examples (GitHub Source, S3 Sink)

.gitignore, charts/kafka-ui/Chart.yaml, charts/kafka-ui/README.md, charts/kafka-ui/templates/deployment.yaml, charts/kafka-ui/templates/networkpolicy-egress.yaml, charts/kafka-ui/templates/networkpolicy-ingress.yaml, charts/kafka-ui/values.yaml
Make it possible to declare extra labels and network egress/ingress rules for the Kafka-UI pod.
Make it possible to declare extra labels (`podLabels`), network egress/ingress rules for the Kafka-UI pod.
I modified `.gitignore` to be able to make this PR but maybe this will have side effects to the application packaging?
=> [kafka-ui chart] Add extra podLabels and ingress/egress custom rules

README.md, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/AdminClientServiceImpl.java, kafka-ui-api/src/main/resources/application-local.yml, kafka-ui-api/src/main/resources/application-sdp.yml, kafka-ui-api/src/main/resources/application.yml, kafka-ui-api/src/test/resources/application-test.yml
* admin-client-timeout set to 30s by default
* unused zookeeper.connection-timeout removed
* documentation to admin-client-timeout param added
=> Kafka API timeout fixes + doc

charts/kafka-ui/Chart.yaml, charts/kafka-ui/values.yaml
With the current image settings the container image cannot be found.
Fix the image registry and repository values.
Fixed the container image settings in the helm values that were changed because of #1215.
=> [kafka-ui chart] Fix image registry

kafka-ui-api/src/main/java/com/provectus/kafka/ui/controller/SchemasController.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/SchemaRegistryService.java
cluster storage usage removed from SchemaRegistryService
=> Refactoring: cluster storage usage removed from SchemaRegistryService

kafka-ui-react-app/src/components/Connect/Details/Overview/__tests__/__snapshots__/Overview.spec.tsx.snap, kafka-ui-react-app/src/components/Topics/Topic/Details/Overview/Overview.tsx, kafka-ui-react-app/src/components/Topics/Topic/Details/Overview/__test__/Overview.spec.tsx, kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx, kafka-ui-react-app/src/components/common/Metrics/Indicator.tsx, kafka-ui-react-app/src/components/common/Metrics/Metrics.styled.tsx, kafka-ui-react-app/src/components/common/Metrics/__tests__/Indicator.spec.tsx
=> Updated topic URP status color.

kafka-ui-react-app/src/components/ConsumerGroups/Details/Details.tsx, kafka-ui-react-app/src/components/ConsumerGroups/Details/__tests__/Details.spec.tsx
**What changes did you make?**
Updated small typo in the UI relevant to the 'Reset Offsets' button.
Not that I'm aware of.
=> Fix small typo with 'offsets' in UI

kafka-ui-react-app/src/components/Schemas/Edit/Edit.tsx
Issues #1388 
I have added condition for checking schema type to be able to open edit schema page for proto type.
=> fixing empty screen issue when opening edit schema for proto type

.github/workflows/helm.yaml
This workflow uses kubeval tool https://kubeval.instrumenta.dev/ in order to test helm chart. 
K8s versions are pulled automatically from kubernetes github repo.
We start from 1.19 version as the newest deprecated by k8s.
resloves: https://github.com/provectus/kafka-ui/issues/1482
=> Add helm chart testing workflow

.github/workflows/release.yaml, charts/kafka-ui/values.yaml
resolves: https://github.com/provectus/kafka-ui/issues/1591
The image is built by this rule:
`image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"`
Solution is to remove image tag from the values.yaml so that a user can specify his own tag if necessary, however, by default the image tag of the version corresponding to the release version is used.
Release version is substituted in release.yaml instead of using constant "latest" appVersion.
=> Specify distinct image tag version for helm chart

charts/kafka-ui/templates/ingress.yaml
To fix this [issue](https://github.com/provectus/kafka-ui/issues/1640) version trashold has been moved down to have overlap with ingress api life cycle
=> Make Ingress resource survive k8s upgrade from 1.21 to 1.22

.github/workflows/frontend.yaml, kafka-ui-react-app/package.json
Now frontend workflow will be triggered with the next param set to 0, what will return non-zero exit code.
`--max-warnings Int   Number of warnings to trigger nonzero exit code - default: -1`
New option to package json is added for CI.
=> frontend wf restrict warnings

kafka-ui-react-app/src/redux/actions/__test__/thunks/connectors.spec.ts, kafka-ui-react-app/src/redux/actions/thunks/connectors.ts
Changed error message when Connector with that name already exists and added the same in tests
=> adding clear message if connector with new name already exists

kafka-ui-react-app/src/components/Topics/Topic/Topic.tsx, kafka-ui-react-app/src/components/Topics/Topic/TopicContainer.tsx, kafka-ui-react-app/src/components/Topics/Topic/__tests__/Topic.spec.tsx
Added a cleanup to reset topic messages when the Topic component is unmounted to prevent displaying old data.
=> Fix topic messages old data persistence

kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.tsx, kafka-ui-react-app/src/components/common/MultiSelect/MultiSelect.styled.ts, kafka-ui-react-app/src/components/common/MultiSelect/__test__/MultiSelect.styled.spec.tsx, kafka-ui-react-app/src/components/common/Search/Search.tsx
1. While live mode is on (active loading) all the controls (search, offset, partitions select) will be disabled.
2. Once "stop loading" is pressed, fetched messages do not disappear, and controls are enabled back again.
=> Improve live tailing.

kafka-ui-react-app/src/components/Brokers/__test__/Brokers.spec.tsx
Added the missing Brokers fetch mock and used it in the tests.
=> Fix test warnings

kafka-ui-react-app/src/components/Topics/List/List.tsx, kafka-ui-react-app/src/components/Topics/List/__tests__/List.spec.tsx
Used localstorage to store user's preference of Show Internal Topics switch option and use that preferred value as the initial state.
It would be better to store the localstorage item keys in constants or even have a typed service for localstorage actions with the names that we use in the project. Because the whole project wasn't done that way, I used the existing conventions to implement the feature. …
=> Persist show internal topics switch state

kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.styled.ts, kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Filters/Filters.tsx
Fixed border-radius style of the seek type select component in Topic Messages Filters component 
**Result**
=> Fix seek type select styles

kafka-ui-react-app/src/components/Topics/List/List.tsx
Open confirmation modal when clear messages is clicked and refetch to update data.
=> Show confirmation modal when clear messages is clicked in topics list

kafka-ui-react-app/src/lib/yupExtended.ts
Added a custom Yup validation error message.
=> Display a human-readable error message for topic custom parameters value

.github/workflows/documentation.yaml
We are going to be deprecating older versions of urlchecker (and there was a change in versioning to match the upstream package so the version only appears earlier) so I wanted to update here to make sure your workflows do not break!
=> Bump urlchecker-action version

kafka-ui-react-app/src/redux/reducers/topics/__test__/reducer.spec.ts, kafka-ui-react-app/src/redux/reducers/topics/topicsSlice.ts
=> Fixing problem of endless loading after deleting multiple topics

kafka-ui-react-app/src/redux/reducers/connect/__test__/reducer.spec.ts, kafka-ui-react-app/src/redux/reducers/connect/connectSlice.ts
=> Fixing connector't tasks count update is not available without refreshing

kafka-ui-react-app/src/components/Connect/Details/Actions/Actions.tsx, kafka-ui-react-app/src/components/common/PageHeading/PageHeading.tsx
Visibility of header and buttons fixed on Connectors page
=> Added buttons wrapping

.github/workflows/branch-deploy.yml, .github/workflows/branch-remove.yml
Using branch name as a identifier for custom deployment was not perfect idea, in some corner cases it is hard to make appropriate identifier which meet kubernetes resource naming conversion and image tags.
By this change we start to use Pull Request number as identifier, it is unique and simple.
**A picture of a cute animal (not …
=> Start use pr number instead of branch name for custom deployments

.github/workflows/build-public-image.yml, .github/workflows/delete-public-image.yml
This PR adds two GitHub workflows:
1. Build and push docker image into public ecr repo by adding tag 'status/image_testing'. Add a comment to the PR with the name of Image Repo.
2. Remove image tag by removing tag or close PR with existing 'status/image_testing' tag. Add comment to the PR that the existing Image tag was removed from Image Repo.
This PR cover [issue](https://github.com/provectus/kafka-ui/issues/2212)
=> Publish and delete docker image in public ecr

charts/kafka-ui/templates/_helpers.tpl, charts/kafka-ui/templates/deployment.yaml
The changes in this PR aim to fix the problem described in this issue
https://github.com/provectus/kafka-ui/issues/2367
=> Allow not specify image.registry in the values of the helm chart

kafka-ui-api/src/main/java/com/provectus/kafka/ui/mapper/DescribeLogDirsMapper.java
Fix #2322 . When NONE type of error is found, it was saving the name as Error message. Adding condition to avoid this behavior.
=> Do not display broker error as "none"

charts/kafka-ui/templates/deployment.yaml
I've added labels required by [istio](https://istio.io/latest/docs/ops/deployment/requirements/#pod-requirements).
Without these labels istio reports traffic coming from kafka-ui to kafka connect and schema registry with a label `source_app` set to `unknown`, which is far from ideal. Visualizations tools like kiali or Grafana dashboards rely on the `source_app` label in istio metrics to present traffic flowing through environments.
Oh, and apparently my IDE has corrected some whitespaces. I can remove those if they don't meet your conventions or you don't want them. 
Their happiness and wellbeing. …
=> add labels required by istio

kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/AbstractEmitter.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/BackwardRecordEmitter.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/emitter/ForwardRecordEmitter.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/analyze/TopicAnalysisService.java
Fixing infinite polls in ForwardRecordEmitter for topic where no record found for last offset (compact topic)
=> ForwardRecordEmitter infinite polls fix

kafka-ui-api/src/main/java/com/provectus/kafka/ui/exception/TopicMetadataException.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/BrokerService.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/FeatureService.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ReactiveAdminClient.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/TopicsService.java, kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
1. ReactiveAdminClient.loadBrokersConfig returns empty map if configs retrieval not supported by kafka backend
2. ReactiveAdminClient.toMone exception unwrapping added
3. FeatureService delete topics enabled set true by default
4. TopicCreationDTO.replicationFactor made optional
**A picture of a cute animal (not mandatory but …
=> Msk serverless support (BE)

kafka-ui-react-app/src/components/Topics/List/BatchActionsBar.tsx, kafka-ui-react-app/src/components/common/NewTable/Table.tsx, kafka-ui-react-app/src/components/common/NewTable/__test__/Table.spec.tsx
**What changes did you make?** BatchActionsBar is always visible from now on but buttons would be disabled in such case
=> Make topic bulk actions buttons always visible

kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/InternalTopic.java
=> Fix topic internal indication

documentation/guides/Protobuf.md, kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/ProtobufFileSerde.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/serdes/builtin/ProtobufFileSerdeTest.java, kafka-ui-api/src/test/resources/sensor.proto
Kafka UI currently supports loading only a single Protobuf file containing all message definitions: https://github.com/provectus/kafka-ui/blob/v0.4.0/documentation/guides/Protobuf.md
While this makes the implementation to load the Protobuf files and create the schema for Kafka UI shorter, it also limits the usefulness of this feature in larger organiziations which did not migrate to a proper schema registry yet.
This change introduces the `kafka.clusters.protobufFiles` setting which takes a list of Protobuf files instead of a single file in `kafka.clusters.protobufFile`.
When both configuration settings are provided, the single file in `protobufFile` is added to the list in `protobufFiles` before loading, so that the change is …
=> Feature: Add support for multiple Protobuf files

kafka-ui-e2e-checks/src/main/java/com/provectus/kafka/ui/utilities/qaseIoUtils/QaseExtension.java
The `QaseExtension` JUnit extension fails with a `NullPointerException` if `QASE_API_TOKEN` is unset.
Ideally, the extension would skip execution if the token was unavailable instead of failing.
<details>
<summary>Stack trace</summary>
```
org.apache.maven.surefire.util.SurefireReflectionException: java.util.ServiceConfigurationError: org.junit.platform.launcher.TestExecutionListener: Provider com.provectus.kafka.ui.utilities.qaseIoUtils.QaseExtension could not be instantiated
at org.apache.maven.surefire.util.ReflectionUtils.instantiateOneArg(ReflectionUtils.java:139)
at org.apache.maven.surefire.booter.ForkedBooter.createProviderInCurrentClassloader(ForkedBooter.java:403)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSa …
```
=> Tests: Fix `NullPointerException` in `QaseExtension` if token is unavailable

kafka-ui-api/pom.xml, kafka-ui-contract/pom.xml, kafka-ui-e2e-checks/pom.xml, kafka-ui-serde-api/pom.xml, pom.xml
- Centralize dependencies in parent POM's `dependencyManagement` section.
- Bump versions of dependencies which have known security issues (open CVEs).
Refs #2805
Refs #2926
Closes #2711 
=> Centralize dependency versions and bump where necessary

documentation/compose/kafka-ui-serdes.yaml, documentation/compose/proto/key-types.proto, documentation/compose/proto/values.proto, documentation/guides/Protobuf.md, documentation/guides/Serialization.md, kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/BuiltInSerde.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/ClusterSerdes.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/SerdeInstance.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/SerdesInitializer.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/Int32Serde.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/Int64Serde.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/ProtobufFileSerde.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/StringSerde.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/UInt32Serde.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/UInt64Serde.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/UuidBinarySerde.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/sr/SchemaRegistrySerde.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/DeserializationService.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/serdes/SerdesInitializerTest.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/serdes/builtin/ProtobufFileSerdeTest.java
Serdes improvements and fixes:
1. Built-in serde's auto-configuration separated from explicit configuration (when properties set in serde configuration)
2. Serdes initialization logic extracted into SerdesInitializer.java
3. docker-compose example with serdes configuration added
4. Serialization.md document fixed
**A picture of a …
=> Serdes improvements and fixes

kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ReactiveAdminClient.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/ReactiveAdminClientTest.java
ReactiveAdminClient::incrementalAlterConfig now replaces whole topic configs, not only setting new one
=> ISSUE-2968: Deleting a config parameter of topic doesn't take effect

kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/AdminClientServiceImpl.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ConsumerGroupService.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ReactiveAdminClient.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/ReactiveAdminClientTest.java
1. ReactiveAdminClient::getClusterVersion now takes into account that controller can not be visible
2. Uniq clientId generation added for consumers and adminClients
3. ReactiveAdminClient::toMonoWithExceptionFilter implementation simplified
=> [BE] Fix a case when controller is not found

kafka-ui-react-app/src/components/App.tsx, kafka-ui-react-app/src/components/Brokers/Brokers.tsx, kafka-ui-react-app/src/components/Connect/Connect.tsx, kafka-ui-react-app/src/components/ErrorPage/ErrorPage.styled.ts, kafka-ui-react-app/src/components/ErrorPage/ErrorPage.tsx, kafka-ui-react-app/src/components/ErrorPage/__tests__/ErrorPage.spec.tsx, kafka-ui-react-app/src/components/Schemas/Details/Details.tsx, kafka-ui-react-app/src/components/Schemas/Edit/Edit.tsx, kafka-ui-react-app/src/components/Schemas/Schemas.tsx, kafka-ui-react-app/src/components/Topics/Topics.tsx, kafka-ui-react-app/src/components/common/SuspenseQueryComponent/SuspenseQueryComponent.tsx, kafka-ui-react-app/src/components/common/SuspenseQueryComponent/__test__/SuspenseQueryComponent.spec.tsx, kafka-ui-react-app/src/lib/paths.ts, kafka-ui-react-app/src/redux/reducers/schemas/schemasSlice.ts, kafka-ui-react-app/src/theme/theme.ts
Handle the Error case when a request 404 flag , that was breaking the page where we were using `Query`, and getting stuck on an infinite load with redux , handle both of them separately, and mention in the issue clear way to migrate to the query case when the times comes.  
**A picture of a cute animal (not mandatory but …
=> Implement 404/403s on FE

kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/Filters.tsx, kafka-ui-react-app/src/components/Topics/Topic/Messages/Messages.tsx, kafka-ui-react-app/src/components/Topics/Topic/Messages/MessagesTable.tsx, kafka-ui-react-app/src/components/Topics/Topic/Messages/__test__/MessagesTable.spec.tsx
I have added next and prev pagination to the old messages page.
=> Messages V1 Pagination 

kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/Filters.tsx
=> Filters Fixing the seekTo parameter when all the partitions are selected

kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/MessagesServiceTest.java
MessagesServiceTest.maskingAppliedOnConfiguredClusters : waiting of kafka write added
=> MessagesServiceTest:maskingAppliedOnConfiguredClusters fix

kafka-ui-react-app/src/components/Wizard/WizardForm/KafkaCluster/KafkaCluster.tsx, kafka-ui-react-app/src/components/Wizard/WizardForm/SchemaRegistry/SchemaRegistry.tsx, kafka-ui-react-app/src/components/Wizard/WizardForm/WizardForm.styled.ts, kafka-ui-react-app/src/components/Wizard/WizardForm/WizardForm.tsx, kafka-ui-react-app/src/components/Wizard/schema.ts
Wizard registry form refactoring
=> refactor Registry Form

documentation/guides/Serialization.md
The `serdes` field does nothing in the `application.conf` and the right one is `serde`. I think it comes from this [line](https://github.com/provectus/kafka-ui/blob/f2ec4d76de481f1a049ae59c4c6fa352bdab7a30/kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/ClustersProperties.java#L41) but I'm not familiar enough with Go to be sure.
We can either change the field name to `serdes` in the `ClusterPropertios` class, or change the docs to fit the field name.
Check out …
=> Fix serialization doc regarding serde configs

kafka-ui-react-app/src/components/Topics/shared/Form/TopicForm.tsx, kafka-ui-react-app/src/components/common/Input/Input.tsx, kafka-ui-react-app/src/components/common/Input/__tests__/Input.spec.tsx, kafka-ui-react-app/src/components/common/NewTable/__test__/Table.spec.tsx
Now user can only input valid digits, and '-' is not allowed in positive-only inputs.
Changed the condition to prevent the key-press event in number input boxes: only accept 0~9 and '-'.
Tested in the browser manually, and now only 0~9 and '-' can be inputted into the box. At the same time, positive-only boxes (like partition count) do not accept '-' anymore. …
=> Fix number of partitions field validation issue

charts/kafka-ui/Chart.yaml, charts/kafka-ui/templates/_helpers.tpl
Now if this chart is used as a subchart, the image registry will be taken from `global.imageRegistry` (if it exists).
* Closes #3437 
I added code that checks if `global.imageRegistry` exists and if so, that will be used instead of `image.registry`. I also bumped the version in `Chart.yaml`.
No
I used the following command: `helm template test charts/kafka-ui/ --set global.imageRegistry=container-registry.my-domain.com | yq e 'select(.kind == "Deployment") | .spec.template.spec.containers[].image'`
**A picture of …
=> Helm: Add the `global.imageRegistry` parameter

kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/Filters.tsx, kafka-ui-react-app/src/lib/hooks/api/ksqlDb.tsx, kafka-ui-react-app/src/lib/hooks/api/topicMessages.tsx
Resolves #3290
Add encoding for clusterName URL parameter
=> HTTP 400 for clusters with special symbols

kafka-ui-react-app/src/components/Topics/Topic/Messages/Message.tsx
Fixes [issue/3250-Dummy field in content ](https://github.com/provectus/kafka-ui/issues/3250)
Following [this comment](https://github.com/provectus/kafka-ui/issues/2675#issuecomment-1386773808), there was a missing `Content` key to be replaced with `Value` when saving a message to JSON or copying it to the clipboard.  
None.
Tested adding a new message, downloading to a file, and checked if the  `Value` key existed instead of the `Content` one.
Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING. …
=> Fix dummy field in saved JSON message content

kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/AddEditFilterContainer.tsx, kafka-ui-react-app/src/components/Topics/Topic/Topic.tsx, kafka-ui-react-app/src/components/Topics/Topic/__test__/Topic.spec.tsx
Implement system redirects to topics after topic delete 
=> Implement system redirects to Topics after topic delete #3044

configuration/helm-charts/configuration.md
This PR is created to support the enhacement identified in the https://github.com/provectus/kafka-ui/issues/3776. It is an initial approach to cover that feature for OpenShift environments. This PR is a complementary for the #3777 to add the documentation of the new parameters to cover that new feature.
This PR should be accepted and merged after the #3777 is merged into the `master` branch. …
=> Add OpenShift route Helm Chart parameters configuration

configuration/helm-charts/quick-start.md
- Rectify the incorrect yamlApplicationConfigConfigMap.name parameter value in the Helm Quick-Start documentation.
- The current configuration map name is excessively lengthy, so I fix it.
- Naming of pre-existing configmap
=> docs: fix configmap parameter name in quick-start.md

README.md
Fixes the value for boolean to be string in yaml
The copy/paste of the yaml in the persistent installtion doesn't work because the `DYNAMIC_CONFIG_ENABLED: true` should be `DYNAMIC_CONFIG_ENABLED: 'true'`
=> Fix typo in persistent installation

kafka-ui-react-app/src/components/App.tsx
react-query didn't initiate requests even for localhost without active internet access.
Changing network mode to `offlineFirst` will make it try once and retry in intervals later if the first attempt was unsuccessful.
Resolves #3865
=> FE: Fix reach query not initiating requests for local host

.gitignore, kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/ProtobufFileSerde.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/serdes/builtin/ProtobufFileSerdeTest.java
Removed "protobufFile" property checks and usage 
https://github.com/provectus/kafka-ui/issues/2893
=> BE: Chore: drop deprecated protobuf single file property. Issue 2893

kafka-ui-react-app/public/robots.txt
=> FE: Add robots.txt

kafka-ui-react-app/src/components/Topics/Topic/Messages/getDefaultSerdeName.ts, kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx, kafka-ui-react-app/src/components/Topics/Topic/SendMessage/utils.ts
…om being generated
Closes #3902
=> FE: Fix Messages: Produce: "Keep contents" not re-generated

kafka-ui-api/pom.xml, kafka-ui-api/src/test/java/com/provectus/kafka/ui/AbstractIntegrationTest.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/ksql/KsqlApiClientTest.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/ksql/KsqlServiceV2Test.java, pom.xml
=> CVE fixes, 07.23

kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/WebClientConfigurator.java
HTTP(S) proxy settings are applied only in some specific cases when `configureSsl` is called with some non-null params. They should be always used.
`GithubReleaseInfo` is not executed properly in our environment.
Checked this branch on our production env:
=> BE: Respect system proxy settings in WebClient

kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ReactiveAdminClient.java
ACL enablement check fixes:
1. Setting 1 hour ConfigRelatedInfo update duration
2. logging ACL checking on debug level
=> ISSUE-3820: ACL enablement check fixes:

kafka-ui-react-app/src/components/NavBar/UserInfo/UserInfo.tsx, kafka-ui-react-app/src/components/NavBar/UserInfo/__tests__/UserInfo.spec.tsx
=> FE: Logout button link is bound to a wrong div

kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/rbac/AccessControlService.java
=> BE: RBAC: Skip rbac checks in case of app config

kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/ClustersProperties.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/permission/AclAction.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/permission/ApplicationConfigAction.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/permission/AuditAction.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/permission/ClusterConfigAction.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/permission/ConnectAction.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/permission/ConsumerGroupAction.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/permission/KsqlAction.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/permission/PermissibleAction.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/permission/SchemaAction.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/rbac/permission/TopicAction.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/audit/AuditRecord.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/audit/AuditService.java, kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/audit/AuditWriter.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/audit/AuditServiceTest.java, kafka-ui-api/src/test/java/com/provectus/kafka/ui/service/audit/AuditWriterTest.java, kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
=> BE: Implement audit log level

kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/BasicAuthSecurityConfig.java
Fixes #4127
Spring does use HTTP GET for OAuth and HTTP POST for login_form for some reason.
Our frontend does use GET and the OAuth filter is hardcoded, so replacing basic to GET
```
LogoutPageGeneratingWebFilter
LogoutWebFilter
```
=> BE: Use HTTP GET for basic auth

kafka-ui-react-app/src/components/Topics/New/New.tsx, kafka-ui-react-app/src/lib/hooks/api/topics.ts, kafka-ui-react-app/src/redux/interfaces/topic.ts
although `retention.bytes` is from "Custom Parameter" when creating topic, it was declared directly in Form and Configs.
so the default value for `retention.bytes` didn't work.
after removed, `retention.bytes` works like other Custom Parameters.
Fixes #4030
=> FE: Topics: Do not send properties which are not defined explicitly

kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/rbac/extractor/CognitoAuthorityExtractor.java
=> BE: Fix cognito roles extractor regression

kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/ApplicationMetrics.java
Common prefix for all application metrics added to make it easier to distinguish kui metrics from other metrics, exposed by spring boot
=> Common prefix for all application metrics
